// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_identity

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func IdentityDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"alias": schema.StringAttribute{
				Computed:            true,
				Description:         "The identity's alternate unique identifier is equivalent to its Account Name on the authoritative source account schema.",
				MarkdownDescription: "The identity's alternate unique identifier is equivalent to its Account Name on the authoritative source account schema.",
			},
			"created": schema.StringAttribute{
				Computed:            true,
				Description:         "Creation date of the identity",
				MarkdownDescription: "Creation date of the identity",
			},
			"email_address": schema.StringAttribute{
				Computed:            true,
				Description:         "The email address of the identity",
				MarkdownDescription: "The email address of the identity",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "Identity Id",
				MarkdownDescription: "Identity Id",
			},
			"identity_status": schema.StringAttribute{
				Computed:            true,
				Description:         "The identity's status in the system",
				MarkdownDescription: "The identity's status in the system",
			},
			"is_manager": schema.BoolAttribute{
				Computed:            true,
				Description:         "Whether this identity is a manager of another identity",
				MarkdownDescription: "Whether this identity is a manager of another identity",
			},
			"last_refresh": schema.StringAttribute{
				Computed:            true,
				Description:         "The last time the identity was refreshed by the system",
				MarkdownDescription: "The last time the identity was refreshed by the system",
			},
			"lifecycle_state": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"manually_updated": schema.BoolAttribute{
						Computed:            true,
						Description:         "Whether the lifecycle state has been manually or automatically set",
						MarkdownDescription: "Whether the lifecycle state has been manually or automatically set",
					},
					"state_name": schema.StringAttribute{
						Computed:            true,
						Description:         "The name of the lifecycle state",
						MarkdownDescription: "The name of the lifecycle state",
					},
				},
				CustomType: LifecycleStateType{
					ObjectType: types.ObjectType{
						AttrTypes: LifecycleStateValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "Lifecycle state details that include lifecycle state name and whether this lifecycle state has been set manually",
				MarkdownDescription: "Lifecycle state details that include lifecycle state name and whether this lifecycle state has been set manually",
			},
			"manager_ref": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed:            true,
						Description:         "ID of identity's manager",
						MarkdownDescription: "ID of identity's manager",
					},
					"name": schema.StringAttribute{
						Computed:            true,
						Description:         "Human-readable display name of identity's manager",
						MarkdownDescription: "Human-readable display name of identity's manager",
					},
					"type": schema.StringAttribute{
						Computed:            true,
						Description:         "DTO type of identity's manager",
						MarkdownDescription: "DTO type of identity's manager",
					},
				},
				CustomType: ManagerRefType{
					ObjectType: types.ObjectType{
						AttrTypes: ManagerRefValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "Identity's manager",
				MarkdownDescription: "Identity's manager",
			},
			"modified": schema.StringAttribute{
				Computed:            true,
				Description:         "Last modification date of the identity",
				MarkdownDescription: "Last modification date of the identity",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "The identity's name is equivalent to its Display Name attribute.",
				MarkdownDescription: "The identity's name is equivalent to its Display Name attribute.",
			},
			"processing_state": schema.StringAttribute{
				Computed:            true,
				Description:         "The processing state of the identity",
				MarkdownDescription: "The processing state of the identity",
			},
		},
	}
}

type IdentityModel struct {
	Alias           types.String        `tfsdk:"alias"`
	Created         types.String        `tfsdk:"created"`
	EmailAddress    types.String        `tfsdk:"email_address"`
	Id              types.String        `tfsdk:"id"`
	IdentityStatus  types.String        `tfsdk:"identity_status"`
	IsManager       types.Bool          `tfsdk:"is_manager"`
	LastRefresh     types.String        `tfsdk:"last_refresh"`
	LifecycleState  LifecycleStateValue `tfsdk:"lifecycle_state"`
	ManagerRef      ManagerRefValue     `tfsdk:"manager_ref"`
	Modified        types.String        `tfsdk:"modified"`
	Name            types.String        `tfsdk:"name"`
	ProcessingState types.String        `tfsdk:"processing_state"`
}

var _ basetypes.ObjectTypable = LifecycleStateType{}

type LifecycleStateType struct {
	basetypes.ObjectType
}

func (t LifecycleStateType) Equal(o attr.Type) bool {
	other, ok := o.(LifecycleStateType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t LifecycleStateType) String() string {
	return "LifecycleStateType"
}

func (t LifecycleStateType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	manuallyUpdatedAttribute, ok := attributes["manually_updated"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`manually_updated is missing from object`)

		return nil, diags
	}

	manuallyUpdatedVal, ok := manuallyUpdatedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`manually_updated expected to be basetypes.BoolValue, was: %T`, manuallyUpdatedAttribute))
	}

	stateNameAttribute, ok := attributes["state_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state_name is missing from object`)

		return nil, diags
	}

	stateNameVal, ok := stateNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state_name expected to be basetypes.StringValue, was: %T`, stateNameAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return LifecycleStateValue{
		ManuallyUpdated: manuallyUpdatedVal,
		StateName:       stateNameVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewLifecycleStateValueNull() LifecycleStateValue {
	return LifecycleStateValue{
		state: attr.ValueStateNull,
	}
}

func NewLifecycleStateValueUnknown() LifecycleStateValue {
	return LifecycleStateValue{
		state: attr.ValueStateUnknown,
	}
}

func NewLifecycleStateValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (LifecycleStateValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing LifecycleStateValue Attribute Value",
				"While creating a LifecycleStateValue value, a missing attribute value was detected. "+
					"A LifecycleStateValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LifecycleStateValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid LifecycleStateValue Attribute Type",
				"While creating a LifecycleStateValue value, an invalid attribute value was detected. "+
					"A LifecycleStateValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LifecycleStateValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("LifecycleStateValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra LifecycleStateValue Attribute Value",
				"While creating a LifecycleStateValue value, an extra attribute value was detected. "+
					"A LifecycleStateValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra LifecycleStateValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewLifecycleStateValueUnknown(), diags
	}

	manuallyUpdatedAttribute, ok := attributes["manually_updated"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`manually_updated is missing from object`)

		return NewLifecycleStateValueUnknown(), diags
	}

	manuallyUpdatedVal, ok := manuallyUpdatedAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`manually_updated expected to be basetypes.BoolValue, was: %T`, manuallyUpdatedAttribute))
	}

	stateNameAttribute, ok := attributes["state_name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state_name is missing from object`)

		return NewLifecycleStateValueUnknown(), diags
	}

	stateNameVal, ok := stateNameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state_name expected to be basetypes.StringValue, was: %T`, stateNameAttribute))
	}

	if diags.HasError() {
		return NewLifecycleStateValueUnknown(), diags
	}

	return LifecycleStateValue{
		ManuallyUpdated: manuallyUpdatedVal,
		StateName:       stateNameVal,
		state:           attr.ValueStateKnown,
	}, diags
}

func NewLifecycleStateValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) LifecycleStateValue {
	object, diags := NewLifecycleStateValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewLifecycleStateValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t LifecycleStateType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewLifecycleStateValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewLifecycleStateValueUnknown(), nil
	}

	if in.IsNull() {
		return NewLifecycleStateValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewLifecycleStateValueMust(LifecycleStateValue{}.AttributeTypes(ctx), attributes), nil
}

func (t LifecycleStateType) ValueType(ctx context.Context) attr.Value {
	return LifecycleStateValue{}
}

var _ basetypes.ObjectValuable = LifecycleStateValue{}

type LifecycleStateValue struct {
	ManuallyUpdated basetypes.BoolValue   `tfsdk:"manually_updated"`
	StateName       basetypes.StringValue `tfsdk:"state_name"`
	state           attr.ValueState
}

func (v LifecycleStateValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["manually_updated"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["state_name"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.ManuallyUpdated.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["manually_updated"] = val

		val, err = v.StateName.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["state_name"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v LifecycleStateValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v LifecycleStateValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v LifecycleStateValue) String() string {
	return "LifecycleStateValue"
}

func (v LifecycleStateValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"manually_updated": basetypes.BoolType{},
		"state_name":       basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"manually_updated": v.ManuallyUpdated,
			"state_name":       v.StateName,
		})

	return objVal, diags
}

func (v LifecycleStateValue) Equal(o attr.Value) bool {
	other, ok := o.(LifecycleStateValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ManuallyUpdated.Equal(other.ManuallyUpdated) {
		return false
	}

	if !v.StateName.Equal(other.StateName) {
		return false
	}

	return true
}

func (v LifecycleStateValue) Type(ctx context.Context) attr.Type {
	return LifecycleStateType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v LifecycleStateValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"manually_updated": basetypes.BoolType{},
		"state_name":       basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ManagerRefType{}

type ManagerRefType struct {
	basetypes.ObjectType
}

func (t ManagerRefType) Equal(o attr.Type) bool {
	other, ok := o.(ManagerRefType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ManagerRefType) String() string {
	return "ManagerRefType"
}

func (t ManagerRefType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ManagerRefValue{
		Id:             idVal,
		Name:           nameVal,
		ManagerRefType: typeVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewManagerRefValueNull() ManagerRefValue {
	return ManagerRefValue{
		state: attr.ValueStateNull,
	}
}

func NewManagerRefValueUnknown() ManagerRefValue {
	return ManagerRefValue{
		state: attr.ValueStateUnknown,
	}
}

func NewManagerRefValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ManagerRefValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ManagerRefValue Attribute Value",
				"While creating a ManagerRefValue value, a missing attribute value was detected. "+
					"A ManagerRefValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ManagerRefValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ManagerRefValue Attribute Type",
				"While creating a ManagerRefValue value, an invalid attribute value was detected. "+
					"A ManagerRefValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ManagerRefValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ManagerRefValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ManagerRefValue Attribute Value",
				"While creating a ManagerRefValue value, an extra attribute value was detected. "+
					"A ManagerRefValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ManagerRefValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewManagerRefValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewManagerRefValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewManagerRefValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewManagerRefValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewManagerRefValueUnknown(), diags
	}

	return ManagerRefValue{
		Id:             idVal,
		Name:           nameVal,
		ManagerRefType: typeVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewManagerRefValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ManagerRefValue {
	object, diags := NewManagerRefValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewManagerRefValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ManagerRefType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewManagerRefValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewManagerRefValueUnknown(), nil
	}

	if in.IsNull() {
		return NewManagerRefValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewManagerRefValueMust(ManagerRefValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ManagerRefType) ValueType(ctx context.Context) attr.Value {
	return ManagerRefValue{}
}

var _ basetypes.ObjectValuable = ManagerRefValue{}

type ManagerRefValue struct {
	Id             basetypes.StringValue `tfsdk:"id"`
	Name           basetypes.StringValue `tfsdk:"name"`
	ManagerRefType basetypes.StringValue `tfsdk:"type"`
	state          attr.ValueState
}

func (v ManagerRefValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.ManagerRefType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ManagerRefValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ManagerRefValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ManagerRefValue) String() string {
	return "ManagerRefValue"
}

func (v ManagerRefValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":   v.Id,
			"name": v.Name,
			"type": v.ManagerRefType,
		})

	return objVal, diags
}

func (v ManagerRefValue) Equal(o attr.Value) bool {
	other, ok := o.(ManagerRefValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.ManagerRefType.Equal(other.ManagerRefType) {
		return false
	}

	return true
}

func (v ManagerRefValue) Type(ctx context.Context) attr.Type {
	return ManagerRefType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ManagerRefValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}
}
