// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_source_provisioning_policy

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SourceProvisioningPolicyResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"description": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "the description of the provisioning policy",
				MarkdownDescription: "the description of the provisioning policy",
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "the provisioning policy name",
				MarkdownDescription: "the provisioning policy name",
			},
			"source_id": schema.StringAttribute{
				Required:            true,
				Description:         "The Source ID.",
				MarkdownDescription: "The Source ID.",
			},
			"usage_type": schema.StringAttribute{
				Required:            true,
				Description:         "The type of provisioning policy usage. \nIn IdentityNow, a source can support various provisioning operations. For example, when a joiner is added to a source, this may trigger both CREATE and UPDATE provisioning operations.  Each usage type is considered a provisioning policy.  A source can have any number of these provisioning policies defined. \nThese are the common usage types: \nCREATE - This usage type relates to 'Create Account Profile', the provisioning template for the account to be created. For example, this would be used for a joiner on a source.  \nUPDATE - This usage type relates to 'Update Account Profile', the provisioning template for the 'Update' connector operations. For example, this would be used for an attribute sync on a source.\nENABLE - This usage type relates to 'Enable Account Profile', the provisioning template for the account to be enabled. For example, this could be used for a joiner on a source once the joiner's account is created. \nDISABLE - This usage type relates to 'Disable Account Profile', the provisioning template for the account to be disabled. For example, this could be used when a leaver is removed temporarily from a source.\nCREATE_MACHINE_ACCOUNT - This usage type can be used to create the provisioning template for a source subtype which will be used in creating a machine account.\nYou can use these usage types for all your provisioning policy needs. ",
				MarkdownDescription: "The type of provisioning policy usage. \nIn IdentityNow, a source can support various provisioning operations. For example, when a joiner is added to a source, this may trigger both CREATE and UPDATE provisioning operations.  Each usage type is considered a provisioning policy.  A source can have any number of these provisioning policies defined. \nThese are the common usage types: \nCREATE - This usage type relates to 'Create Account Profile', the provisioning template for the account to be created. For example, this would be used for a joiner on a source.  \nUPDATE - This usage type relates to 'Update Account Profile', the provisioning template for the 'Update' connector operations. For example, this would be used for an attribute sync on a source.\nENABLE - This usage type relates to 'Enable Account Profile', the provisioning template for the account to be enabled. For example, this could be used for a joiner on a source once the joiner's account is created. \nDISABLE - This usage type relates to 'Disable Account Profile', the provisioning template for the account to be disabled. For example, this could be used when a leaver is removed temporarily from a source.\nCREATE_MACHINE_ACCOUNT - This usage type can be used to create the provisioning template for a source subtype which will be used in creating a machine account.\nYou can use these usage types for all your provisioning policy needs. ",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"CREATE",
						"UPDATE",
						"ENABLE",
						"DISABLE",
						"DELETE",
						"ASSIGN",
						"UNASSIGN",
						"CREATE_GROUP",
						"UPDATE_GROUP",
						"DELETE_GROUP",
						"REGISTER",
						"CREATE_IDENTITY",
						"UPDATE_IDENTITY",
						"EDIT_GROUP",
						"UNLOCK",
						"CHANGE_PASSWORD",
						"CREATE_MACHINE_ACCOUNT",
					),
				},
			},
		},
	}
}

type SourceProvisioningPolicyModel struct {
	Description types.String `tfsdk:"description"`
	Name        types.String `tfsdk:"name"`
	SourceId    types.String `tfsdk:"source_id"`
	UsageType   types.String `tfsdk:"usage_type"`
}
