// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_connector_rule

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ConnectorRuleDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created": schema.StringAttribute{
				Computed:            true,
				Description:         "an ISO 8601 UTC timestamp when this rule was created",
				MarkdownDescription: "an ISO 8601 UTC timestamp when this rule was created",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "a description of the rule's purpose",
				MarkdownDescription: "a description of the rule's purpose",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "ID of the connector rule to get.",
				MarkdownDescription: "ID of the connector rule to get.",
			},
			"modified": schema.StringAttribute{
				Computed:            true,
				Description:         "an ISO 8601 UTC timestamp when this rule was last modified",
				MarkdownDescription: "an ISO 8601 UTC timestamp when this rule was last modified",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "the name of the rule",
				MarkdownDescription: "the name of the rule",
			},
			"signature": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"input": schema.ListNestedAttribute{
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"description": schema.StringAttribute{
									Computed:            true,
									Description:         "the description of the argument",
									MarkdownDescription: "the description of the argument",
								},
								"name": schema.StringAttribute{
									Computed:            true,
									Description:         "the name of the argument",
									MarkdownDescription: "the name of the argument",
								},
								"type": schema.StringAttribute{
									Computed:            true,
									Description:         "the programmatic type of the argument",
									MarkdownDescription: "the programmatic type of the argument",
								},
							},
							CustomType: InputType{
								ObjectType: types.ObjectType{
									AttrTypes: InputValue{}.AttributeTypes(ctx),
								},
							},
						},
						Computed: true,
					},
					"output": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"description": schema.StringAttribute{
								Computed:            true,
								Description:         "the description of the argument",
								MarkdownDescription: "the description of the argument",
							},
							"name": schema.StringAttribute{
								Computed:            true,
								Description:         "the name of the argument",
								MarkdownDescription: "the name of the argument",
							},
							"type": schema.StringAttribute{
								Computed:            true,
								Description:         "the programmatic type of the argument",
								MarkdownDescription: "the programmatic type of the argument",
							},
						},
						CustomType: OutputType{
							ObjectType: types.ObjectType{
								AttrTypes: OutputValue{}.AttributeTypes(ctx),
							},
						},
						Computed: true,
					},
				},
				CustomType: SignatureType{
					ObjectType: types.ObjectType{
						AttrTypes: SignatureValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "The rule's function signature. Describes the rule's input arguments and output (if any)",
				MarkdownDescription: "The rule's function signature. Describes the rule's input arguments and output (if any)",
			},
			"source_code": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"script": schema.StringAttribute{
						Computed:            true,
						Description:         "The code",
						MarkdownDescription: "The code",
					},
					"version": schema.StringAttribute{
						Computed:            true,
						Description:         "the version of the code",
						MarkdownDescription: "the version of the code",
					},
				},
				CustomType: SourceCodeType{
					ObjectType: types.ObjectType{
						AttrTypes: SourceCodeValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "SourceCode",
				MarkdownDescription: "SourceCode",
			},
			"type": schema.StringAttribute{
				Computed:            true,
				Description:         "the type of rule",
				MarkdownDescription: "the type of rule",
			},
		},
	}
}

type ConnectorRuleModel struct {
	Created     types.String    `tfsdk:"created"`
	Description types.String    `tfsdk:"description"`
	Id          types.String    `tfsdk:"id"`
	Modified    types.String    `tfsdk:"modified"`
	Name        types.String    `tfsdk:"name"`
	Signature   SignatureValue  `tfsdk:"signature"`
	SourceCode  SourceCodeValue `tfsdk:"source_code"`
	Type        types.String    `tfsdk:"type"`
}

var _ basetypes.ObjectTypable = SignatureType{}

type SignatureType struct {
	basetypes.ObjectType
}

func (t SignatureType) Equal(o attr.Type) bool {
	other, ok := o.(SignatureType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t SignatureType) String() string {
	return "SignatureType"
}

func (t SignatureType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	inputAttribute, ok := attributes["input"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`input is missing from object`)

		return nil, diags
	}

	inputVal, ok := inputAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`input expected to be basetypes.ListValue, was: %T`, inputAttribute))
	}

	outputAttribute, ok := attributes["output"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`output is missing from object`)

		return nil, diags
	}

	outputVal, ok := outputAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`output expected to be basetypes.ObjectValue, was: %T`, outputAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return SignatureValue{
		Input:  inputVal,
		Output: outputVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewSignatureValueNull() SignatureValue {
	return SignatureValue{
		state: attr.ValueStateNull,
	}
}

func NewSignatureValueUnknown() SignatureValue {
	return SignatureValue{
		state: attr.ValueStateUnknown,
	}
}

func NewSignatureValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (SignatureValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing SignatureValue Attribute Value",
				"While creating a SignatureValue value, a missing attribute value was detected. "+
					"A SignatureValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SignatureValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid SignatureValue Attribute Type",
				"While creating a SignatureValue value, an invalid attribute value was detected. "+
					"A SignatureValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SignatureValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("SignatureValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra SignatureValue Attribute Value",
				"While creating a SignatureValue value, an extra attribute value was detected. "+
					"A SignatureValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra SignatureValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewSignatureValueUnknown(), diags
	}

	inputAttribute, ok := attributes["input"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`input is missing from object`)

		return NewSignatureValueUnknown(), diags
	}

	inputVal, ok := inputAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`input expected to be basetypes.ListValue, was: %T`, inputAttribute))
	}

	outputAttribute, ok := attributes["output"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`output is missing from object`)

		return NewSignatureValueUnknown(), diags
	}

	outputVal, ok := outputAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`output expected to be basetypes.ObjectValue, was: %T`, outputAttribute))
	}

	if diags.HasError() {
		return NewSignatureValueUnknown(), diags
	}

	return SignatureValue{
		Input:  inputVal,
		Output: outputVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewSignatureValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) SignatureValue {
	object, diags := NewSignatureValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewSignatureValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t SignatureType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewSignatureValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewSignatureValueUnknown(), nil
	}

	if in.IsNull() {
		return NewSignatureValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewSignatureValueMust(SignatureValue{}.AttributeTypes(ctx), attributes), nil
}

func (t SignatureType) ValueType(ctx context.Context) attr.Value {
	return SignatureValue{}
}

var _ basetypes.ObjectValuable = SignatureValue{}

type SignatureValue struct {
	Input  basetypes.ListValue   `tfsdk:"input"`
	Output basetypes.ObjectValue `tfsdk:"output"`
	state  attr.ValueState
}

func (v SignatureValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["input"] = basetypes.ListType{
		ElemType: InputValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["output"] = basetypes.ObjectType{
		AttrTypes: OutputValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Input.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["input"] = val

		val, err = v.Output.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["output"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v SignatureValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v SignatureValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v SignatureValue) String() string {
	return "SignatureValue"
}

func (v SignatureValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	input := types.ListValueMust(
		InputType{
			basetypes.ObjectType{
				AttrTypes: InputValue{}.AttributeTypes(ctx),
			},
		},
		v.Input.Elements(),
	)

	if v.Input.IsNull() {
		input = types.ListNull(
			InputType{
				basetypes.ObjectType{
					AttrTypes: InputValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.Input.IsUnknown() {
		input = types.ListUnknown(
			InputType{
				basetypes.ObjectType{
					AttrTypes: InputValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	var output basetypes.ObjectValue

	if v.Output.IsNull() {
		output = types.ObjectNull(
			OutputValue{}.AttributeTypes(ctx),
		)
	}

	if v.Output.IsUnknown() {
		output = types.ObjectUnknown(
			OutputValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Output.IsNull() && !v.Output.IsUnknown() {
		output = types.ObjectValueMust(
			OutputValue{}.AttributeTypes(ctx),
			v.Output.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"input": basetypes.ListType{
			ElemType: InputValue{}.Type(ctx),
		},
		"output": basetypes.ObjectType{
			AttrTypes: OutputValue{}.AttributeTypes(ctx),
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"input":  input,
			"output": output,
		})

	return objVal, diags
}

func (v SignatureValue) Equal(o attr.Value) bool {
	other, ok := o.(SignatureValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Input.Equal(other.Input) {
		return false
	}

	if !v.Output.Equal(other.Output) {
		return false
	}

	return true
}

func (v SignatureValue) Type(ctx context.Context) attr.Type {
	return SignatureType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v SignatureValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"input": basetypes.ListType{
			ElemType: InputValue{}.Type(ctx),
		},
		"output": basetypes.ObjectType{
			AttrTypes: OutputValue{}.AttributeTypes(ctx),
		},
	}
}

var _ basetypes.ObjectTypable = InputType{}

type InputType struct {
	basetypes.ObjectType
}

func (t InputType) Equal(o attr.Type) bool {
	other, ok := o.(InputType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t InputType) String() string {
	return "InputType"
}

func (t InputType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return InputValue{
		Description: descriptionVal,
		Name:        nameVal,
		InputType:   typeVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewInputValueNull() InputValue {
	return InputValue{
		state: attr.ValueStateNull,
	}
}

func NewInputValueUnknown() InputValue {
	return InputValue{
		state: attr.ValueStateUnknown,
	}
}

func NewInputValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (InputValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing InputValue Attribute Value",
				"While creating a InputValue value, a missing attribute value was detected. "+
					"A InputValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("InputValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid InputValue Attribute Type",
				"While creating a InputValue value, an invalid attribute value was detected. "+
					"A InputValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("InputValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("InputValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra InputValue Attribute Value",
				"While creating a InputValue value, an extra attribute value was detected. "+
					"A InputValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra InputValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewInputValueUnknown(), diags
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewInputValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewInputValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewInputValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewInputValueUnknown(), diags
	}

	return InputValue{
		Description: descriptionVal,
		Name:        nameVal,
		InputType:   typeVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewInputValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) InputValue {
	object, diags := NewInputValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewInputValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t InputType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewInputValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewInputValueUnknown(), nil
	}

	if in.IsNull() {
		return NewInputValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewInputValueMust(InputValue{}.AttributeTypes(ctx), attributes), nil
}

func (t InputType) ValueType(ctx context.Context) attr.Value {
	return InputValue{}
}

var _ basetypes.ObjectValuable = InputValue{}

type InputValue struct {
	Description basetypes.StringValue `tfsdk:"description"`
	Name        basetypes.StringValue `tfsdk:"name"`
	InputType   basetypes.StringValue `tfsdk:"type"`
	state       attr.ValueState
}

func (v InputValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.InputType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v InputValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v InputValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v InputValue) String() string {
	return "InputValue"
}

func (v InputValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"description": basetypes.StringType{},
		"name":        basetypes.StringType{},
		"type":        basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"description": v.Description,
			"name":        v.Name,
			"type":        v.InputType,
		})

	return objVal, diags
}

func (v InputValue) Equal(o attr.Value) bool {
	other, ok := o.(InputValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.InputType.Equal(other.InputType) {
		return false
	}

	return true
}

func (v InputValue) Type(ctx context.Context) attr.Type {
	return InputType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v InputValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"description": basetypes.StringType{},
		"name":        basetypes.StringType{},
		"type":        basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = OutputType{}

type OutputType struct {
	basetypes.ObjectType
}

func (t OutputType) Equal(o attr.Type) bool {
	other, ok := o.(OutputType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t OutputType) String() string {
	return "OutputType"
}

func (t OutputType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return OutputValue{
		Description: descriptionVal,
		Name:        nameVal,
		OutputType:  typeVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewOutputValueNull() OutputValue {
	return OutputValue{
		state: attr.ValueStateNull,
	}
}

func NewOutputValueUnknown() OutputValue {
	return OutputValue{
		state: attr.ValueStateUnknown,
	}
}

func NewOutputValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (OutputValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing OutputValue Attribute Value",
				"While creating a OutputValue value, a missing attribute value was detected. "+
					"A OutputValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OutputValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid OutputValue Attribute Type",
				"While creating a OutputValue value, an invalid attribute value was detected. "+
					"A OutputValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OutputValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("OutputValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra OutputValue Attribute Value",
				"While creating a OutputValue value, an extra attribute value was detected. "+
					"A OutputValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra OutputValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewOutputValueUnknown(), diags
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewOutputValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewOutputValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewOutputValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewOutputValueUnknown(), diags
	}

	return OutputValue{
		Description: descriptionVal,
		Name:        nameVal,
		OutputType:  typeVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewOutputValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) OutputValue {
	object, diags := NewOutputValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewOutputValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t OutputType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewOutputValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewOutputValueUnknown(), nil
	}

	if in.IsNull() {
		return NewOutputValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewOutputValueMust(OutputValue{}.AttributeTypes(ctx), attributes), nil
}

func (t OutputType) ValueType(ctx context.Context) attr.Value {
	return OutputValue{}
}

var _ basetypes.ObjectValuable = OutputValue{}

type OutputValue struct {
	Description basetypes.StringValue `tfsdk:"description"`
	Name        basetypes.StringValue `tfsdk:"name"`
	OutputType  basetypes.StringValue `tfsdk:"type"`
	state       attr.ValueState
}

func (v OutputValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.OutputType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v OutputValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v OutputValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v OutputValue) String() string {
	return "OutputValue"
}

func (v OutputValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"description": basetypes.StringType{},
		"name":        basetypes.StringType{},
		"type":        basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"description": v.Description,
			"name":        v.Name,
			"type":        v.OutputType,
		})

	return objVal, diags
}

func (v OutputValue) Equal(o attr.Value) bool {
	other, ok := o.(OutputValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.OutputType.Equal(other.OutputType) {
		return false
	}

	return true
}

func (v OutputValue) Type(ctx context.Context) attr.Type {
	return OutputType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v OutputValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"description": basetypes.StringType{},
		"name":        basetypes.StringType{},
		"type":        basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = SourceCodeType{}

type SourceCodeType struct {
	basetypes.ObjectType
}

func (t SourceCodeType) Equal(o attr.Type) bool {
	other, ok := o.(SourceCodeType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t SourceCodeType) String() string {
	return "SourceCodeType"
}

func (t SourceCodeType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	scriptAttribute, ok := attributes["script"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`script is missing from object`)

		return nil, diags
	}

	scriptVal, ok := scriptAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`script expected to be basetypes.StringValue, was: %T`, scriptAttribute))
	}

	versionAttribute, ok := attributes["version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`version is missing from object`)

		return nil, diags
	}

	versionVal, ok := versionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`version expected to be basetypes.StringValue, was: %T`, versionAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return SourceCodeValue{
		Script:  scriptVal,
		Version: versionVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewSourceCodeValueNull() SourceCodeValue {
	return SourceCodeValue{
		state: attr.ValueStateNull,
	}
}

func NewSourceCodeValueUnknown() SourceCodeValue {
	return SourceCodeValue{
		state: attr.ValueStateUnknown,
	}
}

func NewSourceCodeValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (SourceCodeValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing SourceCodeValue Attribute Value",
				"While creating a SourceCodeValue value, a missing attribute value was detected. "+
					"A SourceCodeValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SourceCodeValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid SourceCodeValue Attribute Type",
				"While creating a SourceCodeValue value, an invalid attribute value was detected. "+
					"A SourceCodeValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SourceCodeValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("SourceCodeValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra SourceCodeValue Attribute Value",
				"While creating a SourceCodeValue value, an extra attribute value was detected. "+
					"A SourceCodeValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra SourceCodeValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewSourceCodeValueUnknown(), diags
	}

	scriptAttribute, ok := attributes["script"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`script is missing from object`)

		return NewSourceCodeValueUnknown(), diags
	}

	scriptVal, ok := scriptAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`script expected to be basetypes.StringValue, was: %T`, scriptAttribute))
	}

	versionAttribute, ok := attributes["version"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`version is missing from object`)

		return NewSourceCodeValueUnknown(), diags
	}

	versionVal, ok := versionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`version expected to be basetypes.StringValue, was: %T`, versionAttribute))
	}

	if diags.HasError() {
		return NewSourceCodeValueUnknown(), diags
	}

	return SourceCodeValue{
		Script:  scriptVal,
		Version: versionVal,
		state:   attr.ValueStateKnown,
	}, diags
}

func NewSourceCodeValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) SourceCodeValue {
	object, diags := NewSourceCodeValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewSourceCodeValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t SourceCodeType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewSourceCodeValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewSourceCodeValueUnknown(), nil
	}

	if in.IsNull() {
		return NewSourceCodeValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewSourceCodeValueMust(SourceCodeValue{}.AttributeTypes(ctx), attributes), nil
}

func (t SourceCodeType) ValueType(ctx context.Context) attr.Value {
	return SourceCodeValue{}
}

var _ basetypes.ObjectValuable = SourceCodeValue{}

type SourceCodeValue struct {
	Script  basetypes.StringValue `tfsdk:"script"`
	Version basetypes.StringValue `tfsdk:"version"`
	state   attr.ValueState
}

func (v SourceCodeValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["script"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["version"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Script.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["script"] = val

		val, err = v.Version.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["version"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v SourceCodeValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v SourceCodeValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v SourceCodeValue) String() string {
	return "SourceCodeValue"
}

func (v SourceCodeValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"script":  basetypes.StringType{},
		"version": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"script":  v.Script,
			"version": v.Version,
		})

	return objVal, diags
}

func (v SourceCodeValue) Equal(o attr.Value) bool {
	other, ok := o.(SourceCodeValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Script.Equal(other.Script) {
		return false
	}

	if !v.Version.Equal(other.Version) {
		return false
	}

	return true
}

func (v SourceCodeValue) Type(ctx context.Context) attr.Type {
	return SourceCodeType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v SourceCodeValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"script":  basetypes.StringType{},
		"version": basetypes.StringType{},
	}
}
