# Syntax: <Application ID>,<Access Profile ID>/<Access Profile ID>/...

terraform import identitynow_application_access_association.association <Application ID>,<Access Profile ID>/<Access Profile ID>/...
