// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_segments

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SegmentsDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"limit": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Max number of results to return.\nSee [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.",
				MarkdownDescription: "Max number of results to return.\nSee [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.",
				Validators: []validator.Int64{
					int64validator.Between(0, 250),
				},
			},
			"offset": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "Offset into the full result set. Usually specified with *limit* to paginate through the results.\nSee [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.",
				MarkdownDescription: "Offset into the full result set. Usually specified with *limit* to paginate through the results.\nSee [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.",
				Validators: []validator.Int64{
					int64validator.AtLeast(0),
				},
			},
			"segments": schema.SetNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"active": schema.BoolAttribute{
							Computed:            true,
							Description:         "This boolean indicates whether the segment is currently active. Inactive segments have no effect.",
							MarkdownDescription: "This boolean indicates whether the segment is currently active. Inactive segments have no effect.",
						},
						"created": schema.StringAttribute{
							Computed:            true,
							Description:         "The time when the segment is created.",
							MarkdownDescription: "The time when the segment is created.",
						},
						"description": schema.StringAttribute{
							Computed:            true,
							Description:         "The segment's optional description.",
							MarkdownDescription: "The segment's optional description.",
						},
						"id": schema.StringAttribute{
							Computed:            true,
							Description:         "The segment's ID.",
							MarkdownDescription: "The segment's ID.",
						},
						"modified": schema.StringAttribute{
							Computed:            true,
							Description:         "The time when the segment is modified.",
							MarkdownDescription: "The time when the segment is modified.",
						},
						"name": schema.StringAttribute{
							Computed:            true,
							Description:         "The segment's business name.",
							MarkdownDescription: "The segment's business name.",
						},
						"owner": schema.SingleNestedAttribute{
							Attributes: map[string]schema.Attribute{
								"id": schema.StringAttribute{
									Computed:            true,
									Description:         "Identity id",
									MarkdownDescription: "Identity id",
								},
								"name": schema.StringAttribute{
									Computed:            true,
									Description:         "Human-readable display name of the owner. It may be left null or omitted in a POST or PATCH. If set, it must match the current value of the owner's display name, otherwise a 400 Bad Request error will result.",
									MarkdownDescription: "Human-readable display name of the owner. It may be left null or omitted in a POST or PATCH. If set, it must match the current value of the owner's display name, otherwise a 400 Bad Request error will result.",
								},
								"type": schema.StringAttribute{
									Computed:            true,
									Description:         "Owner type. This field must be either left null or set to 'IDENTITY' on input, otherwise a 400 Bad Request error will result.",
									MarkdownDescription: "Owner type. This field must be either left null or set to 'IDENTITY' on input, otherwise a 400 Bad Request error will result.",
								},
							},
							CustomType: OwnerType{
								ObjectType: types.ObjectType{
									AttrTypes: OwnerValue{}.AttributeTypes(ctx),
								},
							},
							Computed:            true,
							Description:         "The owner of this object.",
							MarkdownDescription: "The owner of this object.",
						},
					},
					CustomType: SegmentsType{
						ObjectType: types.ObjectType{
							AttrTypes: SegmentsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
		},
	}
}

type SegmentsModel struct {
	Limit    types.Int64 `tfsdk:"limit"`
	Offset   types.Int64 `tfsdk:"offset"`
	Segments types.Set   `tfsdk:"segments"`
}

var _ basetypes.ObjectTypable = SegmentsType{}

type SegmentsType struct {
	basetypes.ObjectType
}

func (t SegmentsType) Equal(o attr.Type) bool {
	other, ok := o.(SegmentsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t SegmentsType) String() string {
	return "SegmentsType"
}

func (t SegmentsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	activeAttribute, ok := attributes["active"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`active is missing from object`)

		return nil, diags
	}

	activeVal, ok := activeAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`active expected to be basetypes.BoolValue, was: %T`, activeAttribute))
	}

	createdAttribute, ok := attributes["created"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created is missing from object`)

		return nil, diags
	}

	createdVal, ok := createdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created expected to be basetypes.StringValue, was: %T`, createdAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	modifiedAttribute, ok := attributes["modified"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`modified is missing from object`)

		return nil, diags
	}

	modifiedVal, ok := modifiedAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`modified expected to be basetypes.StringValue, was: %T`, modifiedAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	ownerAttribute, ok := attributes["owner"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`owner is missing from object`)

		return nil, diags
	}

	ownerVal, ok := ownerAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`owner expected to be basetypes.ObjectValue, was: %T`, ownerAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return SegmentsValue{
		Active:      activeVal,
		Created:     createdVal,
		Description: descriptionVal,
		Id:          idVal,
		Modified:    modifiedVal,
		Name:        nameVal,
		Owner:       ownerVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewSegmentsValueNull() SegmentsValue {
	return SegmentsValue{
		state: attr.ValueStateNull,
	}
}

func NewSegmentsValueUnknown() SegmentsValue {
	return SegmentsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewSegmentsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (SegmentsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing SegmentsValue Attribute Value",
				"While creating a SegmentsValue value, a missing attribute value was detected. "+
					"A SegmentsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SegmentsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid SegmentsValue Attribute Type",
				"While creating a SegmentsValue value, an invalid attribute value was detected. "+
					"A SegmentsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SegmentsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("SegmentsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra SegmentsValue Attribute Value",
				"While creating a SegmentsValue value, an extra attribute value was detected. "+
					"A SegmentsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra SegmentsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewSegmentsValueUnknown(), diags
	}

	activeAttribute, ok := attributes["active"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`active is missing from object`)

		return NewSegmentsValueUnknown(), diags
	}

	activeVal, ok := activeAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`active expected to be basetypes.BoolValue, was: %T`, activeAttribute))
	}

	createdAttribute, ok := attributes["created"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`created is missing from object`)

		return NewSegmentsValueUnknown(), diags
	}

	createdVal, ok := createdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`created expected to be basetypes.StringValue, was: %T`, createdAttribute))
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewSegmentsValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewSegmentsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	modifiedAttribute, ok := attributes["modified"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`modified is missing from object`)

		return NewSegmentsValueUnknown(), diags
	}

	modifiedVal, ok := modifiedAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`modified expected to be basetypes.StringValue, was: %T`, modifiedAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewSegmentsValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	ownerAttribute, ok := attributes["owner"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`owner is missing from object`)

		return NewSegmentsValueUnknown(), diags
	}

	ownerVal, ok := ownerAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`owner expected to be basetypes.ObjectValue, was: %T`, ownerAttribute))
	}

	if diags.HasError() {
		return NewSegmentsValueUnknown(), diags
	}

	return SegmentsValue{
		Active:      activeVal,
		Created:     createdVal,
		Description: descriptionVal,
		Id:          idVal,
		Modified:    modifiedVal,
		Name:        nameVal,
		Owner:       ownerVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewSegmentsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) SegmentsValue {
	object, diags := NewSegmentsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewSegmentsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t SegmentsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewSegmentsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewSegmentsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewSegmentsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewSegmentsValueMust(SegmentsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t SegmentsType) ValueType(ctx context.Context) attr.Value {
	return SegmentsValue{}
}

var _ basetypes.ObjectValuable = SegmentsValue{}

type SegmentsValue struct {
	Active      basetypes.BoolValue   `tfsdk:"active"`
	Created     basetypes.StringValue `tfsdk:"created"`
	Description basetypes.StringValue `tfsdk:"description"`
	Id          basetypes.StringValue `tfsdk:"id"`
	Modified    basetypes.StringValue `tfsdk:"modified"`
	Name        basetypes.StringValue `tfsdk:"name"`
	Owner       basetypes.ObjectValue `tfsdk:"owner"`
	state       attr.ValueState
}

func (v SegmentsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 7)

	var val tftypes.Value
	var err error

	attrTypes["active"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["created"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["modified"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["owner"] = basetypes.ObjectType{
		AttrTypes: OwnerValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 7)

		val, err = v.Active.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["active"] = val

		val, err = v.Created.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["created"] = val

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Modified.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["modified"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Owner.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["owner"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v SegmentsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v SegmentsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v SegmentsValue) String() string {
	return "SegmentsValue"
}

func (v SegmentsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var owner basetypes.ObjectValue

	if v.Owner.IsNull() {
		owner = types.ObjectNull(
			OwnerValue{}.AttributeTypes(ctx),
		)
	}

	if v.Owner.IsUnknown() {
		owner = types.ObjectUnknown(
			OwnerValue{}.AttributeTypes(ctx),
		)
	}

	if !v.Owner.IsNull() && !v.Owner.IsUnknown() {
		owner = types.ObjectValueMust(
			OwnerValue{}.AttributeTypes(ctx),
			v.Owner.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"active":      basetypes.BoolType{},
		"created":     basetypes.StringType{},
		"description": basetypes.StringType{},
		"id":          basetypes.StringType{},
		"modified":    basetypes.StringType{},
		"name":        basetypes.StringType{},
		"owner": basetypes.ObjectType{
			AttrTypes: OwnerValue{}.AttributeTypes(ctx),
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"active":      v.Active,
			"created":     v.Created,
			"description": v.Description,
			"id":          v.Id,
			"modified":    v.Modified,
			"name":        v.Name,
			"owner":       owner,
		})

	return objVal, diags
}

func (v SegmentsValue) Equal(o attr.Value) bool {
	other, ok := o.(SegmentsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Active.Equal(other.Active) {
		return false
	}

	if !v.Created.Equal(other.Created) {
		return false
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Modified.Equal(other.Modified) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Owner.Equal(other.Owner) {
		return false
	}

	return true
}

func (v SegmentsValue) Type(ctx context.Context) attr.Type {
	return SegmentsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v SegmentsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"active":      basetypes.BoolType{},
		"created":     basetypes.StringType{},
		"description": basetypes.StringType{},
		"id":          basetypes.StringType{},
		"modified":    basetypes.StringType{},
		"name":        basetypes.StringType{},
		"owner": basetypes.ObjectType{
			AttrTypes: OwnerValue{}.AttributeTypes(ctx),
		},
	}
}

var _ basetypes.ObjectTypable = OwnerType{}

type OwnerType struct {
	basetypes.ObjectType
}

func (t OwnerType) Equal(o attr.Type) bool {
	other, ok := o.(OwnerType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t OwnerType) String() string {
	return "OwnerType"
}

func (t OwnerType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return OwnerValue{
		Id:        idVal,
		Name:      nameVal,
		OwnerType: typeVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewOwnerValueNull() OwnerValue {
	return OwnerValue{
		state: attr.ValueStateNull,
	}
}

func NewOwnerValueUnknown() OwnerValue {
	return OwnerValue{
		state: attr.ValueStateUnknown,
	}
}

func NewOwnerValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (OwnerValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing OwnerValue Attribute Value",
				"While creating a OwnerValue value, a missing attribute value was detected. "+
					"A OwnerValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OwnerValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid OwnerValue Attribute Type",
				"While creating a OwnerValue value, an invalid attribute value was detected. "+
					"A OwnerValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OwnerValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("OwnerValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra OwnerValue Attribute Value",
				"While creating a OwnerValue value, an extra attribute value was detected. "+
					"A OwnerValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra OwnerValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewOwnerValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewOwnerValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewOwnerValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewOwnerValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewOwnerValueUnknown(), diags
	}

	return OwnerValue{
		Id:        idVal,
		Name:      nameVal,
		OwnerType: typeVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewOwnerValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) OwnerValue {
	object, diags := NewOwnerValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewOwnerValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t OwnerType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewOwnerValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewOwnerValueUnknown(), nil
	}

	if in.IsNull() {
		return NewOwnerValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewOwnerValueMust(OwnerValue{}.AttributeTypes(ctx), attributes), nil
}

func (t OwnerType) ValueType(ctx context.Context) attr.Value {
	return OwnerValue{}
}

var _ basetypes.ObjectValuable = OwnerValue{}

type OwnerValue struct {
	Id        basetypes.StringValue `tfsdk:"id"`
	Name      basetypes.StringValue `tfsdk:"name"`
	OwnerType basetypes.StringValue `tfsdk:"type"`
	state     attr.ValueState
}

func (v OwnerValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.OwnerType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v OwnerValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v OwnerValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v OwnerValue) String() string {
	return "OwnerValue"
}

func (v OwnerValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":   v.Id,
			"name": v.Name,
			"type": v.OwnerType,
		})

	return objVal, diags
}

func (v OwnerValue) Equal(o attr.Value) bool {
	other, ok := o.(OwnerValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.OwnerType.Equal(other.OwnerType) {
		return false
	}

	return true
}

func (v OwnerValue) Type(ctx context.Context) attr.Type {
	return OwnerType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v OwnerValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}
}
