// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_application

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ApplicationDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"account_source": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed:            true,
						Description:         "The source ID",
						MarkdownDescription: "The source ID",
					},
					"name": schema.StringAttribute{
						Computed:            true,
						Description:         "The source name",
						MarkdownDescription: "The source name",
					},
					"password_policies": schema.ListNestedAttribute{
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"id": schema.StringAttribute{
									Computed:            true,
									Description:         "ID of the object to which this reference applies",
									MarkdownDescription: "ID of the object to which this reference applies",
								},
								"name": schema.StringAttribute{
									Computed:            true,
									Description:         "Human-readable display name of the object to which this reference applies",
									MarkdownDescription: "Human-readable display name of the object to which this reference applies",
								},
								"type": schema.StringAttribute{
									Computed:            true,
									Description:         "DTO type",
									MarkdownDescription: "DTO type",
								},
							},
							CustomType: PasswordPoliciesType{
								ObjectType: types.ObjectType{
									AttrTypes: PasswordPoliciesValue{}.AttributeTypes(ctx),
								},
							},
						},
						Computed:            true,
						Description:         "The password policies for the source",
						MarkdownDescription: "The password policies for the source",
					},
					"type": schema.StringAttribute{
						Computed:            true,
						Description:         "The source type, will always be \"SOURCE\"",
						MarkdownDescription: "The source type, will always be \"SOURCE\"",
					},
					"use_for_password_management": schema.BoolAttribute{
						Computed:            true,
						Description:         "If the source is used for password management",
						MarkdownDescription: "If the source is used for password management",
					},
				},
				CustomType: AccountSourceType{
					ObjectType: types.ObjectType{
						AttrTypes: AccountSourceValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"app_center_enabled": schema.BoolAttribute{
				Computed:            true,
				Description:         "True if the app is visible in the request center",
				MarkdownDescription: "True if the app is visible in the request center",
			},
			"cloud_app_id": schema.StringAttribute{
				Computed:            true,
				Description:         "The deprecated source app id",
				MarkdownDescription: "The deprecated source app id",
			},
			"created": schema.StringAttribute{
				Computed:            true,
				Description:         "Time when the source app was created",
				MarkdownDescription: "Time when the source app was created",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "The description of the source app",
				MarkdownDescription: "The description of the source app",
			},
			"enabled": schema.BoolAttribute{
				Computed:            true,
				Description:         "True if the source app is enabled",
				MarkdownDescription: "True if the source app is enabled",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "ID of the source app",
				MarkdownDescription: "ID of the source app",
			},
			"match_all_accounts": schema.BoolAttribute{
				Computed:            true,
				Description:         "True if the source app match all accounts",
				MarkdownDescription: "True if the source app match all accounts",
			},
			"modified": schema.StringAttribute{
				Computed:            true,
				Description:         "Time when the source app was last modified",
				MarkdownDescription: "Time when the source app was last modified",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "The source app name",
				MarkdownDescription: "The source app name",
			},
			"owner": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed:            true,
						Description:         "ID of the object to which this reference applies",
						MarkdownDescription: "ID of the object to which this reference applies",
					},
					"name": schema.StringAttribute{
						Computed:            true,
						Description:         "Human-readable display name of the object to which this reference applies",
						MarkdownDescription: "Human-readable display name of the object to which this reference applies",
					},
					"type": schema.StringAttribute{
						Computed:            true,
						Description:         "DTO type",
						MarkdownDescription: "DTO type",
					},
				},
				CustomType: OwnerType{
					ObjectType: types.ObjectType{
						AttrTypes: OwnerValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "The owner of source app",
				MarkdownDescription: "The owner of source app",
			},
			"provision_request_enabled": schema.BoolAttribute{
				Computed:            true,
				Description:         "True if the app allows access request",
				MarkdownDescription: "True if the app allows access request",
			},
		},
	}
}

type ApplicationModel struct {
	AccountSource           AccountSourceValue `tfsdk:"account_source"`
	AppCenterEnabled        types.Bool         `tfsdk:"app_center_enabled"`
	CloudAppId              types.String       `tfsdk:"cloud_app_id"`
	Created                 types.String       `tfsdk:"created"`
	Description             types.String       `tfsdk:"description"`
	Enabled                 types.Bool         `tfsdk:"enabled"`
	Id                      types.String       `tfsdk:"id"`
	MatchAllAccounts        types.Bool         `tfsdk:"match_all_accounts"`
	Modified                types.String       `tfsdk:"modified"`
	Name                    types.String       `tfsdk:"name"`
	Owner                   OwnerValue         `tfsdk:"owner"`
	ProvisionRequestEnabled types.Bool         `tfsdk:"provision_request_enabled"`
}

var _ basetypes.ObjectTypable = AccountSourceType{}

type AccountSourceType struct {
	basetypes.ObjectType
}

func (t AccountSourceType) Equal(o attr.Type) bool {
	other, ok := o.(AccountSourceType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AccountSourceType) String() string {
	return "AccountSourceType"
}

func (t AccountSourceType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	passwordPoliciesAttribute, ok := attributes["password_policies"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`password_policies is missing from object`)

		return nil, diags
	}

	passwordPoliciesVal, ok := passwordPoliciesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`password_policies expected to be basetypes.ListValue, was: %T`, passwordPoliciesAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	useForPasswordManagementAttribute, ok := attributes["use_for_password_management"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`use_for_password_management is missing from object`)

		return nil, diags
	}

	useForPasswordManagementVal, ok := useForPasswordManagementAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`use_for_password_management expected to be basetypes.BoolValue, was: %T`, useForPasswordManagementAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AccountSourceValue{
		Id:                       idVal,
		Name:                     nameVal,
		PasswordPolicies:         passwordPoliciesVal,
		AccountSourceType:        typeVal,
		UseForPasswordManagement: useForPasswordManagementVal,
		state:                    attr.ValueStateKnown,
	}, diags
}

func NewAccountSourceValueNull() AccountSourceValue {
	return AccountSourceValue{
		state: attr.ValueStateNull,
	}
}

func NewAccountSourceValueUnknown() AccountSourceValue {
	return AccountSourceValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAccountSourceValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AccountSourceValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AccountSourceValue Attribute Value",
				"While creating a AccountSourceValue value, a missing attribute value was detected. "+
					"A AccountSourceValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AccountSourceValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AccountSourceValue Attribute Type",
				"While creating a AccountSourceValue value, an invalid attribute value was detected. "+
					"A AccountSourceValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AccountSourceValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AccountSourceValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AccountSourceValue Attribute Value",
				"While creating a AccountSourceValue value, an extra attribute value was detected. "+
					"A AccountSourceValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AccountSourceValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAccountSourceValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewAccountSourceValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewAccountSourceValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	passwordPoliciesAttribute, ok := attributes["password_policies"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`password_policies is missing from object`)

		return NewAccountSourceValueUnknown(), diags
	}

	passwordPoliciesVal, ok := passwordPoliciesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`password_policies expected to be basetypes.ListValue, was: %T`, passwordPoliciesAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewAccountSourceValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	useForPasswordManagementAttribute, ok := attributes["use_for_password_management"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`use_for_password_management is missing from object`)

		return NewAccountSourceValueUnknown(), diags
	}

	useForPasswordManagementVal, ok := useForPasswordManagementAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`use_for_password_management expected to be basetypes.BoolValue, was: %T`, useForPasswordManagementAttribute))
	}

	if diags.HasError() {
		return NewAccountSourceValueUnknown(), diags
	}

	return AccountSourceValue{
		Id:                       idVal,
		Name:                     nameVal,
		PasswordPolicies:         passwordPoliciesVal,
		AccountSourceType:        typeVal,
		UseForPasswordManagement: useForPasswordManagementVal,
		state:                    attr.ValueStateKnown,
	}, diags
}

func NewAccountSourceValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AccountSourceValue {
	object, diags := NewAccountSourceValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAccountSourceValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AccountSourceType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAccountSourceValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAccountSourceValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAccountSourceValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAccountSourceValueMust(AccountSourceValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AccountSourceType) ValueType(ctx context.Context) attr.Value {
	return AccountSourceValue{}
}

var _ basetypes.ObjectValuable = AccountSourceValue{}

type AccountSourceValue struct {
	Id                       basetypes.StringValue `tfsdk:"id"`
	Name                     basetypes.StringValue `tfsdk:"name"`
	PasswordPolicies         basetypes.ListValue   `tfsdk:"password_policies"`
	AccountSourceType        basetypes.StringValue `tfsdk:"type"`
	UseForPasswordManagement basetypes.BoolValue   `tfsdk:"use_for_password_management"`
	state                    attr.ValueState
}

func (v AccountSourceValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["password_policies"] = basetypes.ListType{
		ElemType: PasswordPoliciesValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["use_for_password_management"] = basetypes.BoolType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.PasswordPolicies.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["password_policies"] = val

		val, err = v.AccountSourceType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		val, err = v.UseForPasswordManagement.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["use_for_password_management"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AccountSourceValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AccountSourceValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AccountSourceValue) String() string {
	return "AccountSourceValue"
}

func (v AccountSourceValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	passwordPolicies := types.ListValueMust(
		PasswordPoliciesType{
			basetypes.ObjectType{
				AttrTypes: PasswordPoliciesValue{}.AttributeTypes(ctx),
			},
		},
		v.PasswordPolicies.Elements(),
	)

	if v.PasswordPolicies.IsNull() {
		passwordPolicies = types.ListNull(
			PasswordPoliciesType{
				basetypes.ObjectType{
					AttrTypes: PasswordPoliciesValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.PasswordPolicies.IsUnknown() {
		passwordPolicies = types.ListUnknown(
			PasswordPoliciesType{
				basetypes.ObjectType{
					AttrTypes: PasswordPoliciesValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	attributeTypes := map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"password_policies": basetypes.ListType{
			ElemType: PasswordPoliciesValue{}.Type(ctx),
		},
		"type":                        basetypes.StringType{},
		"use_for_password_management": basetypes.BoolType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":                          v.Id,
			"name":                        v.Name,
			"password_policies":           passwordPolicies,
			"type":                        v.AccountSourceType,
			"use_for_password_management": v.UseForPasswordManagement,
		})

	return objVal, diags
}

func (v AccountSourceValue) Equal(o attr.Value) bool {
	other, ok := o.(AccountSourceValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.PasswordPolicies.Equal(other.PasswordPolicies) {
		return false
	}

	if !v.AccountSourceType.Equal(other.AccountSourceType) {
		return false
	}

	if !v.UseForPasswordManagement.Equal(other.UseForPasswordManagement) {
		return false
	}

	return true
}

func (v AccountSourceValue) Type(ctx context.Context) attr.Type {
	return AccountSourceType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AccountSourceValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"password_policies": basetypes.ListType{
			ElemType: PasswordPoliciesValue{}.Type(ctx),
		},
		"type":                        basetypes.StringType{},
		"use_for_password_management": basetypes.BoolType{},
	}
}

var _ basetypes.ObjectTypable = PasswordPoliciesType{}

type PasswordPoliciesType struct {
	basetypes.ObjectType
}

func (t PasswordPoliciesType) Equal(o attr.Type) bool {
	other, ok := o.(PasswordPoliciesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t PasswordPoliciesType) String() string {
	return "PasswordPoliciesType"
}

func (t PasswordPoliciesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return PasswordPoliciesValue{
		Id:                   idVal,
		Name:                 nameVal,
		PasswordPoliciesType: typeVal,
		state:                attr.ValueStateKnown,
	}, diags
}

func NewPasswordPoliciesValueNull() PasswordPoliciesValue {
	return PasswordPoliciesValue{
		state: attr.ValueStateNull,
	}
}

func NewPasswordPoliciesValueUnknown() PasswordPoliciesValue {
	return PasswordPoliciesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewPasswordPoliciesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (PasswordPoliciesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing PasswordPoliciesValue Attribute Value",
				"While creating a PasswordPoliciesValue value, a missing attribute value was detected. "+
					"A PasswordPoliciesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PasswordPoliciesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid PasswordPoliciesValue Attribute Type",
				"While creating a PasswordPoliciesValue value, an invalid attribute value was detected. "+
					"A PasswordPoliciesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PasswordPoliciesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("PasswordPoliciesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra PasswordPoliciesValue Attribute Value",
				"While creating a PasswordPoliciesValue value, an extra attribute value was detected. "+
					"A PasswordPoliciesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra PasswordPoliciesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewPasswordPoliciesValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewPasswordPoliciesValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewPasswordPoliciesValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewPasswordPoliciesValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewPasswordPoliciesValueUnknown(), diags
	}

	return PasswordPoliciesValue{
		Id:                   idVal,
		Name:                 nameVal,
		PasswordPoliciesType: typeVal,
		state:                attr.ValueStateKnown,
	}, diags
}

func NewPasswordPoliciesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) PasswordPoliciesValue {
	object, diags := NewPasswordPoliciesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewPasswordPoliciesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t PasswordPoliciesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewPasswordPoliciesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewPasswordPoliciesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewPasswordPoliciesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewPasswordPoliciesValueMust(PasswordPoliciesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t PasswordPoliciesType) ValueType(ctx context.Context) attr.Value {
	return PasswordPoliciesValue{}
}

var _ basetypes.ObjectValuable = PasswordPoliciesValue{}

type PasswordPoliciesValue struct {
	Id                   basetypes.StringValue `tfsdk:"id"`
	Name                 basetypes.StringValue `tfsdk:"name"`
	PasswordPoliciesType basetypes.StringValue `tfsdk:"type"`
	state                attr.ValueState
}

func (v PasswordPoliciesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.PasswordPoliciesType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v PasswordPoliciesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v PasswordPoliciesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v PasswordPoliciesValue) String() string {
	return "PasswordPoliciesValue"
}

func (v PasswordPoliciesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":   v.Id,
			"name": v.Name,
			"type": v.PasswordPoliciesType,
		})

	return objVal, diags
}

func (v PasswordPoliciesValue) Equal(o attr.Value) bool {
	other, ok := o.(PasswordPoliciesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.PasswordPoliciesType.Equal(other.PasswordPoliciesType) {
		return false
	}

	return true
}

func (v PasswordPoliciesValue) Type(ctx context.Context) attr.Type {
	return PasswordPoliciesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v PasswordPoliciesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = OwnerType{}

type OwnerType struct {
	basetypes.ObjectType
}

func (t OwnerType) Equal(o attr.Type) bool {
	other, ok := o.(OwnerType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t OwnerType) String() string {
	return "OwnerType"
}

func (t OwnerType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return OwnerValue{
		Id:        idVal,
		Name:      nameVal,
		OwnerType: typeVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewOwnerValueNull() OwnerValue {
	return OwnerValue{
		state: attr.ValueStateNull,
	}
}

func NewOwnerValueUnknown() OwnerValue {
	return OwnerValue{
		state: attr.ValueStateUnknown,
	}
}

func NewOwnerValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (OwnerValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing OwnerValue Attribute Value",
				"While creating a OwnerValue value, a missing attribute value was detected. "+
					"A OwnerValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OwnerValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid OwnerValue Attribute Type",
				"While creating a OwnerValue value, an invalid attribute value was detected. "+
					"A OwnerValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OwnerValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("OwnerValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra OwnerValue Attribute Value",
				"While creating a OwnerValue value, an extra attribute value was detected. "+
					"A OwnerValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra OwnerValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewOwnerValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewOwnerValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewOwnerValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewOwnerValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewOwnerValueUnknown(), diags
	}

	return OwnerValue{
		Id:        idVal,
		Name:      nameVal,
		OwnerType: typeVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewOwnerValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) OwnerValue {
	object, diags := NewOwnerValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewOwnerValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t OwnerType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewOwnerValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewOwnerValueUnknown(), nil
	}

	if in.IsNull() {
		return NewOwnerValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewOwnerValueMust(OwnerValue{}.AttributeTypes(ctx), attributes), nil
}

func (t OwnerType) ValueType(ctx context.Context) attr.Value {
	return OwnerValue{}
}

var _ basetypes.ObjectValuable = OwnerValue{}

type OwnerValue struct {
	Id        basetypes.StringValue `tfsdk:"id"`
	Name      basetypes.StringValue `tfsdk:"name"`
	OwnerType basetypes.StringValue `tfsdk:"type"`
	state     attr.ValueState
}

func (v OwnerValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.OwnerType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v OwnerValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v OwnerValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v OwnerValue) String() string {
	return "OwnerValue"
}

func (v OwnerValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":   v.Id,
			"name": v.Name,
			"type": v.OwnerType,
		})

	return objVal, diags
}

func (v OwnerValue) Equal(o attr.Value) bool {
	other, ok := o.(OwnerValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.OwnerType.Equal(other.OwnerType) {
		return false
	}

	return true
}

func (v OwnerValue) Type(ctx context.Context) attr.Type {
	return OwnerType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v OwnerValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}
}
