// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_service_desk_integration

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"github.com/sailpoint-oss/golang-sdk/v2/api_beta"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func ServiceDeskIntegrationDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"attributes": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{},
				CustomType: AttributesType{
					ObjectType: types.ObjectType{
						AttrTypes: AttributesValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "Service Desk integration's attributes. Validation constraints enforced by the implementation.",
				MarkdownDescription: "Service Desk integration's attributes. Validation constraints enforced by the implementation.",
			},
			"before_provisioning_rule": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed:            true,
						Description:         "Before Provisioning Rule ID.",
						MarkdownDescription: "Before Provisioning Rule ID.",
					},
					"name": schema.StringAttribute{
						Computed:            true,
						Description:         "Rule display name.",
						MarkdownDescription: "Rule display name.",
					},
					"type": schema.StringAttribute{
						Computed:            true,
						Description:         "Before Provisioning Rule DTO type.",
						MarkdownDescription: "Before Provisioning Rule DTO type.",
					},
				},
				CustomType: BeforeProvisioningRuleType{
					ObjectType: types.ObjectType{
						AttrTypes: BeforeProvisioningRuleValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "Before Provisioning Rule.",
				MarkdownDescription: "Before Provisioning Rule.",
			},
			"cluster": schema.StringAttribute{
				Computed:            true,
				Description:         "Cluster ID for the Service Desk integration (replaced by clusterRef, retained for backward compatibility).",
				MarkdownDescription: "Cluster ID for the Service Desk integration (replaced by clusterRef, retained for backward compatibility).",
				DeprecationMessage:  "This attribute is deprecated.",
			},
			"cluster_ref": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed:            true,
						Description:         "Source cluster ID.",
						MarkdownDescription: "Source cluster ID.",
					},
					"name": schema.StringAttribute{
						Computed:            true,
						Description:         "Source cluster display name.",
						MarkdownDescription: "Source cluster display name.",
					},
					"type": schema.StringAttribute{
						Computed:            true,
						Description:         "Source cluster DTO type.",
						MarkdownDescription: "Source cluster DTO type.",
					},
				},
				CustomType: ClusterRefType{
					ObjectType: types.ObjectType{
						AttrTypes: ClusterRefValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "Source cluster.",
				MarkdownDescription: "Source cluster.",
			},
			"created": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time the Service Desk integration was created",
				MarkdownDescription: "The date and time the Service Desk integration was created",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "Service Desk integration's description.",
				MarkdownDescription: "Service Desk integration's description.",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "ID of the Service Desk integration to get",
				MarkdownDescription: "ID of the Service Desk integration to get",
			},
			"managed_sources": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "Source IDs for the Service Desk integration (replaced by provisioningConfig.managedSResourceRefs, but retained here for backward compatibility).",
				MarkdownDescription: "Source IDs for the Service Desk integration (replaced by provisioningConfig.managedSResourceRefs, but retained here for backward compatibility).",
				DeprecationMessage:  "This attribute is deprecated.",
			},
			"modified": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time the Service Desk integration was last modified",
				MarkdownDescription: "The date and time the Service Desk integration was last modified",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Service Desk integration's name. The name must be unique.",
				MarkdownDescription: "Service Desk integration's name. The name must be unique.",
			},
			"owner_ref": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed:            true,
						Description:         "Owner's identity ID.",
						MarkdownDescription: "Owner's identity ID.",
					},
					"name": schema.StringAttribute{
						Computed:            true,
						Description:         "Owner's name.",
						MarkdownDescription: "Owner's name.",
					},
					"type": schema.StringAttribute{
						Computed:            true,
						Description:         "Owner's DTO type.",
						MarkdownDescription: "Owner's DTO type.",
					},
				},
				CustomType: OwnerRefType{
					ObjectType: types.ObjectType{
						AttrTypes: OwnerRefValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "Owner's identity.",
				MarkdownDescription: "Owner's identity.",
			},
			"provisioning_config": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"managed_resource_refs": schema.ListNestedAttribute{
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"id": schema.StringAttribute{
									Computed:            true,
									Description:         "ID of source for service desk integration template.",
									MarkdownDescription: "ID of source for service desk integration template.",
								},
								"name": schema.StringAttribute{
									Computed:            true,
									Description:         "Human-readable name of source for service desk integration template.",
									MarkdownDescription: "Human-readable name of source for service desk integration template.",
								},
								"type": schema.StringAttribute{
									Computed:            true,
									Description:         "DTO type of source for service desk integration template.",
									MarkdownDescription: "DTO type of source for service desk integration template.",
								},
							},
							CustomType: ManagedResourceRefsType{
								ObjectType: types.ObjectType{
									AttrTypes: ManagedResourceRefsValue{}.AttributeTypes(ctx),
								},
							},
						},
						Computed:            true,
						Description:         "References to sources for the Service Desk integration template.  May only be specified if universalManager is false.",
						MarkdownDescription: "References to sources for the Service Desk integration template.  May only be specified if universalManager is false.",
					},
					"no_provisioning_requests": schema.BoolAttribute{
						Computed:            true,
						Description:         "Name of an attribute that when true disables the saving of ProvisioningRequest objects whenever plans are sent through this integration.",
						MarkdownDescription: "Name of an attribute that when true disables the saving of ProvisioningRequest objects whenever plans are sent through this integration.",
					},
					"plan_initializer_script": schema.SingleNestedAttribute{
						Attributes: map[string]schema.Attribute{
							"source": schema.StringAttribute{
								Computed:            true,
								Description:         "This is a Rule that allows provisioning instruction changes.",
								MarkdownDescription: "This is a Rule that allows provisioning instruction changes.",
							},
						},
						CustomType: PlanInitializerScriptType{
							ObjectType: types.ObjectType{
								AttrTypes: PlanInitializerScriptValue{}.AttributeTypes(ctx),
							},
						},
						Computed:            true,
						Description:         "This is a reference to a plan initializer script.",
						MarkdownDescription: "This is a reference to a plan initializer script.",
					},
					"provisioning_request_expiration": schema.Int64Attribute{
						Computed:            true,
						Description:         "When saving pending requests is enabled, this defines the number of hours the request is allowed to live before it is considered expired and no longer affects plan compilation.",
						MarkdownDescription: "When saving pending requests is enabled, this defines the number of hours the request is allowed to live before it is considered expired and no longer affects plan compilation.",
					},
					"universal_manager": schema.BoolAttribute{
						Computed:            true,
						Description:         "Specifies whether this configuration is used to manage provisioning requests for all sources from the org.  If true, no managedResourceRefs are allowed.",
						MarkdownDescription: "Specifies whether this configuration is used to manage provisioning requests for all sources from the org.  If true, no managedResourceRefs are allowed.",
					},
				},
				CustomType: ProvisioningConfigType{
					ObjectType: types.ObjectType{
						AttrTypes: ProvisioningConfigValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "The 'provisioningConfig' property specifies the configuration used to provision integrations.",
				MarkdownDescription: "The 'provisioningConfig' property specifies the configuration used to provision integrations.",
			},
			"type": schema.StringAttribute{
				Computed:            true,
				Description:         "Service Desk integration types:\n\n- ServiceNowSDIM\n- ServiceNow\n",
				MarkdownDescription: "Service Desk integration types:\n\n- ServiceNowSDIM\n- ServiceNow\n",
			},
		},
	}
}

type ServiceDeskIntegrationModel struct {
	Attributes             AttributesValue             `tfsdk:"attributes"`
	BeforeProvisioningRule BeforeProvisioningRuleValue `tfsdk:"before_provisioning_rule"`
	Cluster                types.String                `tfsdk:"cluster"`
	ClusterRef             ClusterRefValue             `tfsdk:"cluster_ref"`
	Created                types.String                `tfsdk:"created"`
	Description            types.String                `tfsdk:"description"`
	Id                     types.String                `tfsdk:"id"`
	ManagedSources         types.List                  `tfsdk:"managed_sources"`
	Modified               types.String                `tfsdk:"modified"`
	Name                   types.String                `tfsdk:"name"`
	OwnerRef               OwnerRefValue               `tfsdk:"owner_ref"`
	ProvisioningConfig     ProvisioningConfigValue     `tfsdk:"provisioning_config"`
	Type                   types.String                `tfsdk:"type"`
}

var _ basetypes.ObjectTypable = AttributesType{}

type AttributesType struct {
	basetypes.ObjectType
}

func (t AttributesType) Equal(o attr.Type) bool {
	other, ok := o.(AttributesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AttributesType) String() string {
	return "AttributesType"
}

func (t AttributesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	if diags.HasError() {
		return nil, diags
	}

	return AttributesValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewAttributesValueNull() AttributesValue {
	return AttributesValue{
		state: attr.ValueStateNull,
	}
}

func NewAttributesValueUnknown() AttributesValue {
	return AttributesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAttributesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AttributesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AttributesValue Attribute Value",
				"While creating a AttributesValue value, a missing attribute value was detected. "+
					"A AttributesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AttributesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AttributesValue Attribute Type",
				"While creating a AttributesValue value, an invalid attribute value was detected. "+
					"A AttributesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AttributesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AttributesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AttributesValue Attribute Value",
				"While creating a AttributesValue value, an extra attribute value was detected. "+
					"A AttributesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AttributesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAttributesValueUnknown(), diags
	}

	if diags.HasError() {
		return NewAttributesValueUnknown(), diags
	}

	return AttributesValue{
		state: attr.ValueStateKnown,
	}, diags
}

func NewAttributesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AttributesValue {
	object, diags := NewAttributesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAttributesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AttributesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAttributesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAttributesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAttributesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAttributesValueMust(AttributesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AttributesType) ValueType(ctx context.Context) attr.Value {
	return AttributesValue{}
}

var _ basetypes.ObjectValuable = AttributesValue{}

type AttributesValue struct {
	state attr.ValueState
}

func (v AttributesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 0)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 0)

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AttributesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AttributesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AttributesValue) String() string {
	return "AttributesValue"
}

func (v AttributesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{})

	return objVal, diags
}

func (v AttributesValue) Equal(o attr.Value) bool {
	other, ok := o.(AttributesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	return true
}

func (v AttributesValue) Type(ctx context.Context) attr.Type {
	return AttributesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AttributesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{}
}

var _ basetypes.ObjectTypable = BeforeProvisioningRuleType{}

type BeforeProvisioningRuleType struct {
	basetypes.ObjectType
}

func (t BeforeProvisioningRuleType) Equal(o attr.Type) bool {
	other, ok := o.(BeforeProvisioningRuleType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t BeforeProvisioningRuleType) String() string {
	return "BeforeProvisioningRuleType"
}

func (t BeforeProvisioningRuleType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return BeforeProvisioningRuleValue{
		Id:                         idVal,
		Name:                       nameVal,
		BeforeProvisioningRuleType: typeVal,
		state:                      attr.ValueStateKnown,
	}, diags
}

func NewBeforeProvisioningRuleValueNull() BeforeProvisioningRuleValue {
	return BeforeProvisioningRuleValue{
		state: attr.ValueStateNull,
	}
}

func NewBeforeProvisioningRuleValueUnknown() BeforeProvisioningRuleValue {
	return BeforeProvisioningRuleValue{
		state: attr.ValueStateUnknown,
	}
}

func NewBeforeProvisioningRuleValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (BeforeProvisioningRuleValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing BeforeProvisioningRuleValue Attribute Value",
				"While creating a BeforeProvisioningRuleValue value, a missing attribute value was detected. "+
					"A BeforeProvisioningRuleValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("BeforeProvisioningRuleValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid BeforeProvisioningRuleValue Attribute Type",
				"While creating a BeforeProvisioningRuleValue value, an invalid attribute value was detected. "+
					"A BeforeProvisioningRuleValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("BeforeProvisioningRuleValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("BeforeProvisioningRuleValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra BeforeProvisioningRuleValue Attribute Value",
				"While creating a BeforeProvisioningRuleValue value, an extra attribute value was detected. "+
					"A BeforeProvisioningRuleValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra BeforeProvisioningRuleValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewBeforeProvisioningRuleValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewBeforeProvisioningRuleValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewBeforeProvisioningRuleValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewBeforeProvisioningRuleValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewBeforeProvisioningRuleValueUnknown(), diags
	}

	return BeforeProvisioningRuleValue{
		Id:                         idVal,
		Name:                       nameVal,
		BeforeProvisioningRuleType: typeVal,
		state:                      attr.ValueStateKnown,
	}, diags
}

func NewBeforeProvisioningRuleValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) BeforeProvisioningRuleValue {
	object, diags := NewBeforeProvisioningRuleValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewBeforeProvisioningRuleValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t BeforeProvisioningRuleType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewBeforeProvisioningRuleValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewBeforeProvisioningRuleValueUnknown(), nil
	}

	if in.IsNull() {
		return NewBeforeProvisioningRuleValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewBeforeProvisioningRuleValueMust(BeforeProvisioningRuleValue{}.AttributeTypes(ctx), attributes), nil
}

func (t BeforeProvisioningRuleType) ValueType(ctx context.Context) attr.Value {
	return BeforeProvisioningRuleValue{}
}

var _ basetypes.ObjectValuable = BeforeProvisioningRuleValue{}

type BeforeProvisioningRuleValue struct {
	Id                         basetypes.StringValue `tfsdk:"id"`
	Name                       basetypes.StringValue `tfsdk:"name"`
	BeforeProvisioningRuleType basetypes.StringValue `tfsdk:"type"`
	state                      attr.ValueState
}

func (v BeforeProvisioningRuleValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.BeforeProvisioningRuleType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v BeforeProvisioningRuleValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v BeforeProvisioningRuleValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v BeforeProvisioningRuleValue) String() string {
	return "BeforeProvisioningRuleValue"
}

func (v BeforeProvisioningRuleValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":   v.Id,
			"name": v.Name,
			"type": v.BeforeProvisioningRuleType,
		})

	return objVal, diags
}

func (v BeforeProvisioningRuleValue) Equal(o attr.Value) bool {
	other, ok := o.(BeforeProvisioningRuleValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.BeforeProvisioningRuleType.Equal(other.BeforeProvisioningRuleType) {
		return false
	}

	return true
}

func (v BeforeProvisioningRuleValue) Type(ctx context.Context) attr.Type {
	return BeforeProvisioningRuleType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v BeforeProvisioningRuleValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ClusterRefType{}

type ClusterRefType struct {
	basetypes.ObjectType
}

func (t ClusterRefType) Equal(o attr.Type) bool {
	other, ok := o.(ClusterRefType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ClusterRefType) String() string {
	return "ClusterRefType"
}

func (t ClusterRefType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ClusterRefValue{
		Id:             idVal,
		Name:           nameVal,
		ClusterRefType: typeVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewClusterRefValueNull() ClusterRefValue {
	return ClusterRefValue{
		state: attr.ValueStateNull,
	}
}

func NewClusterRefValueUnknown() ClusterRefValue {
	return ClusterRefValue{
		state: attr.ValueStateUnknown,
	}
}

func NewClusterRefValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ClusterRefValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ClusterRefValue Attribute Value",
				"While creating a ClusterRefValue value, a missing attribute value was detected. "+
					"A ClusterRefValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ClusterRefValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ClusterRefValue Attribute Type",
				"While creating a ClusterRefValue value, an invalid attribute value was detected. "+
					"A ClusterRefValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ClusterRefValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ClusterRefValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ClusterRefValue Attribute Value",
				"While creating a ClusterRefValue value, an extra attribute value was detected. "+
					"A ClusterRefValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ClusterRefValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewClusterRefValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewClusterRefValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewClusterRefValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewClusterRefValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewClusterRefValueUnknown(), diags
	}

	return ClusterRefValue{
		Id:             idVal,
		Name:           nameVal,
		ClusterRefType: typeVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewClusterRefValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ClusterRefValue {
	object, diags := NewClusterRefValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewClusterRefValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ClusterRefType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewClusterRefValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewClusterRefValueUnknown(), nil
	}

	if in.IsNull() {
		return NewClusterRefValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewClusterRefValueMust(ClusterRefValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ClusterRefType) ValueType(ctx context.Context) attr.Value {
	return ClusterRefValue{}
}

var _ basetypes.ObjectValuable = ClusterRefValue{}

type ClusterRefValue struct {
	Id             basetypes.StringValue `tfsdk:"id"`
	Name           basetypes.StringValue `tfsdk:"name"`
	ClusterRefType basetypes.StringValue `tfsdk:"type"`
	state          attr.ValueState
}

func (v ClusterRefValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.ClusterRefType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ClusterRefValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ClusterRefValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ClusterRefValue) String() string {
	return "ClusterRefValue"
}

func (v ClusterRefValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":   v.Id,
			"name": v.Name,
			"type": v.ClusterRefType,
		})

	return objVal, diags
}

func (v ClusterRefValue) Equal(o attr.Value) bool {
	other, ok := o.(ClusterRefValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.ClusterRefType.Equal(other.ClusterRefType) {
		return false
	}

	return true
}

func (v ClusterRefValue) Type(ctx context.Context) attr.Type {
	return ClusterRefType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ClusterRefValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = OwnerRefType{}

type OwnerRefType struct {
	basetypes.ObjectType
}

func (t OwnerRefType) Equal(o attr.Type) bool {
	other, ok := o.(OwnerRefType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t OwnerRefType) String() string {
	return "OwnerRefType"
}

func (t OwnerRefType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return OwnerRefValue{
		Id:           idVal,
		Name:         nameVal,
		OwnerRefType: typeVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewOwnerRefValueNull() OwnerRefValue {
	return OwnerRefValue{
		state: attr.ValueStateNull,
	}
}

func NewOwnerRefValueUnknown() OwnerRefValue {
	return OwnerRefValue{
		state: attr.ValueStateUnknown,
	}
}

func NewOwnerRefValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (OwnerRefValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing OwnerRefValue Attribute Value",
				"While creating a OwnerRefValue value, a missing attribute value was detected. "+
					"A OwnerRefValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OwnerRefValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid OwnerRefValue Attribute Type",
				"While creating a OwnerRefValue value, an invalid attribute value was detected. "+
					"A OwnerRefValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OwnerRefValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("OwnerRefValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra OwnerRefValue Attribute Value",
				"While creating a OwnerRefValue value, an extra attribute value was detected. "+
					"A OwnerRefValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra OwnerRefValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewOwnerRefValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewOwnerRefValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewOwnerRefValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewOwnerRefValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewOwnerRefValueUnknown(), diags
	}

	return OwnerRefValue{
		Id:           idVal,
		Name:         nameVal,
		OwnerRefType: typeVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewOwnerRefValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) OwnerRefValue {
	object, diags := NewOwnerRefValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewOwnerRefValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t OwnerRefType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewOwnerRefValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewOwnerRefValueUnknown(), nil
	}

	if in.IsNull() {
		return NewOwnerRefValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewOwnerRefValueMust(OwnerRefValue{}.AttributeTypes(ctx), attributes), nil
}

func (t OwnerRefType) ValueType(ctx context.Context) attr.Value {
	return OwnerRefValue{}
}

var _ basetypes.ObjectValuable = OwnerRefValue{}

type OwnerRefValue struct {
	Id           basetypes.StringValue `tfsdk:"id"`
	Name         basetypes.StringValue `tfsdk:"name"`
	OwnerRefType basetypes.StringValue `tfsdk:"type"`
	state        attr.ValueState
}

func (v OwnerRefValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.OwnerRefType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v OwnerRefValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v OwnerRefValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v OwnerRefValue) String() string {
	return "OwnerRefValue"
}

func (v OwnerRefValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":   v.Id,
			"name": v.Name,
			"type": v.OwnerRefType,
		})

	return objVal, diags
}

func (v OwnerRefValue) Equal(o attr.Value) bool {
	other, ok := o.(OwnerRefValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.OwnerRefType.Equal(other.OwnerRefType) {
		return false
	}

	return true
}

func (v OwnerRefValue) Type(ctx context.Context) attr.Type {
	return OwnerRefType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v OwnerRefValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ProvisioningConfigType{}

type ProvisioningConfigType struct {
	basetypes.ObjectType
}

func (t ProvisioningConfigType) Equal(o attr.Type) bool {
	other, ok := o.(ProvisioningConfigType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ProvisioningConfigType) String() string {
	return "ProvisioningConfigType"
}

func (t ProvisioningConfigType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	managedResourceRefsAttribute, ok := attributes["managed_resource_refs"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`managed_resource_refs is missing from object`)

		return nil, diags
	}

	managedResourceRefsVal, ok := managedResourceRefsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`managed_resource_refs expected to be basetypes.ListValue, was: %T`, managedResourceRefsAttribute))
	}

	noProvisioningRequestsAttribute, ok := attributes["no_provisioning_requests"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`no_provisioning_requests is missing from object`)

		return nil, diags
	}

	noProvisioningRequestsVal, ok := noProvisioningRequestsAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`no_provisioning_requests expected to be basetypes.BoolValue, was: %T`, noProvisioningRequestsAttribute))
	}

	planInitializerScriptAttribute, ok := attributes["plan_initializer_script"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`plan_initializer_script is missing from object`)

		return nil, diags
	}

	planInitializerScriptVal, ok := planInitializerScriptAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`plan_initializer_script expected to be basetypes.ObjectValue, was: %T`, planInitializerScriptAttribute))
	}

	provisioningRequestExpirationAttribute, ok := attributes["provisioning_request_expiration"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`provisioning_request_expiration is missing from object`)

		return nil, diags
	}

	provisioningRequestExpirationVal, ok := provisioningRequestExpirationAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`provisioning_request_expiration expected to be basetypes.Int64Value, was: %T`, provisioningRequestExpirationAttribute))
	}

	universalManagerAttribute, ok := attributes["universal_manager"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`universal_manager is missing from object`)

		return nil, diags
	}

	universalManagerVal, ok := universalManagerAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`universal_manager expected to be basetypes.BoolValue, was: %T`, universalManagerAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ProvisioningConfigValue{
		ManagedResourceRefs:           managedResourceRefsVal,
		NoProvisioningRequests:        noProvisioningRequestsVal,
		PlanInitializerScript:         planInitializerScriptVal,
		ProvisioningRequestExpiration: provisioningRequestExpirationVal,
		UniversalManager:              universalManagerVal,
		state:                         attr.ValueStateKnown,
	}, diags
}

func NewProvisioningConfigValueNull() ProvisioningConfigValue {
	return ProvisioningConfigValue{
		state: attr.ValueStateNull,
	}
}

func NewProvisioningConfigValueUnknown() ProvisioningConfigValue {
	return ProvisioningConfigValue{
		state: attr.ValueStateUnknown,
	}
}

func NewProvisioningConfigValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ProvisioningConfigValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ProvisioningConfigValue Attribute Value",
				"While creating a ProvisioningConfigValue value, a missing attribute value was detected. "+
					"A ProvisioningConfigValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ProvisioningConfigValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ProvisioningConfigValue Attribute Type",
				"While creating a ProvisioningConfigValue value, an invalid attribute value was detected. "+
					"A ProvisioningConfigValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ProvisioningConfigValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ProvisioningConfigValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ProvisioningConfigValue Attribute Value",
				"While creating a ProvisioningConfigValue value, an extra attribute value was detected. "+
					"A ProvisioningConfigValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ProvisioningConfigValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewProvisioningConfigValueUnknown(), diags
	}

	managedResourceRefsAttribute, ok := attributes["managed_resource_refs"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`managed_resource_refs is missing from object`)

		return NewProvisioningConfigValueUnknown(), diags
	}

	managedResourceRefsVal, ok := managedResourceRefsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`managed_resource_refs expected to be basetypes.ListValue, was: %T`, managedResourceRefsAttribute))
	}

	noProvisioningRequestsAttribute, ok := attributes["no_provisioning_requests"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`no_provisioning_requests is missing from object`)

		return NewProvisioningConfigValueUnknown(), diags
	}

	noProvisioningRequestsVal, ok := noProvisioningRequestsAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`no_provisioning_requests expected to be basetypes.BoolValue, was: %T`, noProvisioningRequestsAttribute))
	}

	planInitializerScriptAttribute, ok := attributes["plan_initializer_script"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`plan_initializer_script is missing from object`)

		return NewProvisioningConfigValueUnknown(), diags
	}

	planInitializerScriptVal, ok := planInitializerScriptAttribute.(basetypes.ObjectValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`plan_initializer_script expected to be basetypes.ObjectValue, was: %T`, planInitializerScriptAttribute))
	}

	provisioningRequestExpirationAttribute, ok := attributes["provisioning_request_expiration"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`provisioning_request_expiration is missing from object`)

		return NewProvisioningConfigValueUnknown(), diags
	}

	provisioningRequestExpirationVal, ok := provisioningRequestExpirationAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`provisioning_request_expiration expected to be basetypes.Int64Value, was: %T`, provisioningRequestExpirationAttribute))
	}

	universalManagerAttribute, ok := attributes["universal_manager"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`universal_manager is missing from object`)

		return NewProvisioningConfigValueUnknown(), diags
	}

	universalManagerVal, ok := universalManagerAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`universal_manager expected to be basetypes.BoolValue, was: %T`, universalManagerAttribute))
	}

	if diags.HasError() {
		return NewProvisioningConfigValueUnknown(), diags
	}

	return ProvisioningConfigValue{
		ManagedResourceRefs:           managedResourceRefsVal,
		NoProvisioningRequests:        noProvisioningRequestsVal,
		PlanInitializerScript:         planInitializerScriptVal,
		ProvisioningRequestExpiration: provisioningRequestExpirationVal,
		UniversalManager:              universalManagerVal,
		state:                         attr.ValueStateKnown,
	}, diags
}

func NewProvisioningConfigValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ProvisioningConfigValue {
	object, diags := NewProvisioningConfigValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewProvisioningConfigValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ProvisioningConfigType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewProvisioningConfigValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewProvisioningConfigValueUnknown(), nil
	}

	if in.IsNull() {
		return NewProvisioningConfigValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewProvisioningConfigValueMust(ProvisioningConfigValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ProvisioningConfigType) ValueType(ctx context.Context) attr.Value {
	return ProvisioningConfigValue{}
}

var _ basetypes.ObjectValuable = ProvisioningConfigValue{}

type ProvisioningConfigValue struct {
	ManagedResourceRefs           basetypes.ListValue   `tfsdk:"managed_resource_refs"`
	NoProvisioningRequests        basetypes.BoolValue   `tfsdk:"no_provisioning_requests"`
	PlanInitializerScript         basetypes.ObjectValue `tfsdk:"plan_initializer_script"`
	ProvisioningRequestExpiration basetypes.Int64Value  `tfsdk:"provisioning_request_expiration"`
	UniversalManager              basetypes.BoolValue   `tfsdk:"universal_manager"`
	state                         attr.ValueState
}

func (v ProvisioningConfigValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["managed_resource_refs"] = basetypes.ListType{
		ElemType: ManagedResourceRefsValue{}.Type(ctx),
	}.TerraformType(ctx)
	attrTypes["no_provisioning_requests"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["plan_initializer_script"] = basetypes.ObjectType{
		AttrTypes: PlanInitializerScriptValue{}.AttributeTypes(ctx),
	}.TerraformType(ctx)
	attrTypes["provisioning_request_expiration"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["universal_manager"] = basetypes.BoolType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.ManagedResourceRefs.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["managed_resource_refs"] = val

		val, err = v.NoProvisioningRequests.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["no_provisioning_requests"] = val

		val, err = v.PlanInitializerScript.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["plan_initializer_script"] = val

		val, err = v.ProvisioningRequestExpiration.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["provisioning_request_expiration"] = val

		val, err = v.UniversalManager.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["universal_manager"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ProvisioningConfigValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ProvisioningConfigValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ProvisioningConfigValue) String() string {
	return "ProvisioningConfigValue"
}

func (v ProvisioningConfigValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	managedResourceRefs := types.ListValueMust(
		ManagedResourceRefsType{
			basetypes.ObjectType{
				AttrTypes: ManagedResourceRefsValue{}.AttributeTypes(ctx),
			},
		},
		v.ManagedResourceRefs.Elements(),
	)

	if v.ManagedResourceRefs.IsNull() {
		managedResourceRefs = types.ListNull(
			ManagedResourceRefsType{
				basetypes.ObjectType{
					AttrTypes: ManagedResourceRefsValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.ManagedResourceRefs.IsUnknown() {
		managedResourceRefs = types.ListUnknown(
			ManagedResourceRefsType{
				basetypes.ObjectType{
					AttrTypes: ManagedResourceRefsValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	var planInitializerScript basetypes.ObjectValue

	if v.PlanInitializerScript.IsNull() {
		planInitializerScript = types.ObjectNull(
			PlanInitializerScriptValue{}.AttributeTypes(ctx),
		)
	}

	if v.PlanInitializerScript.IsUnknown() {
		planInitializerScript = types.ObjectUnknown(
			PlanInitializerScriptValue{}.AttributeTypes(ctx),
		)
	}

	if !v.PlanInitializerScript.IsNull() && !v.PlanInitializerScript.IsUnknown() {
		planInitializerScript = types.ObjectValueMust(
			PlanInitializerScriptValue{}.AttributeTypes(ctx),
			v.PlanInitializerScript.Attributes(),
		)
	}

	attributeTypes := map[string]attr.Type{
		"managed_resource_refs": basetypes.ListType{
			ElemType: ManagedResourceRefsValue{}.Type(ctx),
		},
		"no_provisioning_requests": basetypes.BoolType{},
		"plan_initializer_script": basetypes.ObjectType{
			AttrTypes: PlanInitializerScriptValue{}.AttributeTypes(ctx),
		},
		"provisioning_request_expiration": basetypes.Int64Type{},
		"universal_manager":               basetypes.BoolType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"managed_resource_refs":           managedResourceRefs,
			"no_provisioning_requests":        v.NoProvisioningRequests,
			"plan_initializer_script":         planInitializerScript,
			"provisioning_request_expiration": v.ProvisioningRequestExpiration,
			"universal_manager":               v.UniversalManager,
		})

	return objVal, diags
}

func (v ProvisioningConfigValue) Equal(o attr.Value) bool {
	other, ok := o.(ProvisioningConfigValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.ManagedResourceRefs.Equal(other.ManagedResourceRefs) {
		return false
	}

	if !v.NoProvisioningRequests.Equal(other.NoProvisioningRequests) {
		return false
	}

	if !v.PlanInitializerScript.Equal(other.PlanInitializerScript) {
		return false
	}

	if !v.ProvisioningRequestExpiration.Equal(other.ProvisioningRequestExpiration) {
		return false
	}

	if !v.UniversalManager.Equal(other.UniversalManager) {
		return false
	}

	return true
}

func (v ProvisioningConfigValue) Type(ctx context.Context) attr.Type {
	return ProvisioningConfigType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ProvisioningConfigValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"managed_resource_refs": basetypes.ListType{
			ElemType: ManagedResourceRefsValue{}.Type(ctx),
		},
		"no_provisioning_requests": basetypes.BoolType{},
		"plan_initializer_script": basetypes.ObjectType{
			AttrTypes: PlanInitializerScriptValue{}.AttributeTypes(ctx),
		},
		"provisioning_request_expiration": basetypes.Int64Type{},
		"universal_manager":               basetypes.BoolType{},
	}
}

var _ basetypes.ObjectTypable = ManagedResourceRefsType{}

type ManagedResourceRefsType struct {
	basetypes.ObjectType
}

func (t ManagedResourceRefsType) Equal(o attr.Type) bool {
	other, ok := o.(ManagedResourceRefsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ManagedResourceRefsType) String() string {
	return "ManagedResourceRefsType"
}

func (t ManagedResourceRefsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ManagedResourceRefsValue{
		Id:                      idVal,
		Name:                    nameVal,
		ManagedResourceRefsType: typeVal,
		state:                   attr.ValueStateKnown,
	}, diags
}

func NewManagedResourceRefsValueNull() ManagedResourceRefsValue {
	return ManagedResourceRefsValue{
		state: attr.ValueStateNull,
	}
}

func NewManagedResourceRefsValueUnknown() ManagedResourceRefsValue {
	return ManagedResourceRefsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewManagedResourceRefsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ManagedResourceRefsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ManagedResourceRefsValue Attribute Value",
				"While creating a ManagedResourceRefsValue value, a missing attribute value was detected. "+
					"A ManagedResourceRefsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ManagedResourceRefsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ManagedResourceRefsValue Attribute Type",
				"While creating a ManagedResourceRefsValue value, an invalid attribute value was detected. "+
					"A ManagedResourceRefsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ManagedResourceRefsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ManagedResourceRefsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ManagedResourceRefsValue Attribute Value",
				"While creating a ManagedResourceRefsValue value, an extra attribute value was detected. "+
					"A ManagedResourceRefsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ManagedResourceRefsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewManagedResourceRefsValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewManagedResourceRefsValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewManagedResourceRefsValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewManagedResourceRefsValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewManagedResourceRefsValueUnknown(), diags
	}

	return ManagedResourceRefsValue{
		Id:                      idVal,
		Name:                    nameVal,
		ManagedResourceRefsType: typeVal,
		state:                   attr.ValueStateKnown,
	}, diags
}

func NewManagedResourceRefsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ManagedResourceRefsValue {
	object, diags := NewManagedResourceRefsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewManagedResourceRefsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ManagedResourceRefsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewManagedResourceRefsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewManagedResourceRefsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewManagedResourceRefsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewManagedResourceRefsValueMust(ManagedResourceRefsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ManagedResourceRefsType) ValueType(ctx context.Context) attr.Value {
	return ManagedResourceRefsValue{}
}

var _ basetypes.ObjectValuable = ManagedResourceRefsValue{}

type ManagedResourceRefsValue struct {
	Id                      basetypes.StringValue `tfsdk:"id"`
	Name                    basetypes.StringValue `tfsdk:"name"`
	ManagedResourceRefsType basetypes.StringValue `tfsdk:"type"`
	state                   attr.ValueState
}

func (v ManagedResourceRefsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.ManagedResourceRefsType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ManagedResourceRefsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ManagedResourceRefsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ManagedResourceRefsValue) String() string {
	return "ManagedResourceRefsValue"
}

func (v ManagedResourceRefsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":   v.Id,
			"name": v.Name,
			"type": v.ManagedResourceRefsType,
		})

	return objVal, diags
}

func (v ManagedResourceRefsValue) Equal(o attr.Value) bool {
	other, ok := o.(ManagedResourceRefsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.ManagedResourceRefsType.Equal(other.ManagedResourceRefsType) {
		return false
	}

	return true
}

func (v ManagedResourceRefsValue) Type(ctx context.Context) attr.Type {
	return ManagedResourceRefsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ManagedResourceRefsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = PlanInitializerScriptType{}

type PlanInitializerScriptType struct {
	basetypes.ObjectType
}

func (t PlanInitializerScriptType) Equal(o attr.Type) bool {
	other, ok := o.(PlanInitializerScriptType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t PlanInitializerScriptType) String() string {
	return "PlanInitializerScriptType"
}

func (t PlanInitializerScriptType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	sourceAttribute, ok := attributes["source"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`source is missing from object`)

		return nil, diags
	}

	sourceVal, ok := sourceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`source expected to be basetypes.StringValue, was: %T`, sourceAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return PlanInitializerScriptValue{
		Source: sourceVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewPlanInitializerScriptValueNull() PlanInitializerScriptValue {
	return PlanInitializerScriptValue{
		state: attr.ValueStateNull,
	}
}

func NewPlanInitializerScriptValueUnknown() PlanInitializerScriptValue {
	return PlanInitializerScriptValue{
		state: attr.ValueStateUnknown,
	}
}

func NewPlanInitializerScriptValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (PlanInitializerScriptValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing PlanInitializerScriptValue Attribute Value",
				"While creating a PlanInitializerScriptValue value, a missing attribute value was detected. "+
					"A PlanInitializerScriptValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PlanInitializerScriptValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid PlanInitializerScriptValue Attribute Type",
				"While creating a PlanInitializerScriptValue value, an invalid attribute value was detected. "+
					"A PlanInitializerScriptValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PlanInitializerScriptValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("PlanInitializerScriptValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra PlanInitializerScriptValue Attribute Value",
				"While creating a PlanInitializerScriptValue value, an extra attribute value was detected. "+
					"A PlanInitializerScriptValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra PlanInitializerScriptValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewPlanInitializerScriptValueUnknown(), diags
	}

	sourceAttribute, ok := attributes["source"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`source is missing from object`)

		return NewPlanInitializerScriptValueUnknown(), diags
	}

	sourceVal, ok := sourceAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`source expected to be basetypes.StringValue, was: %T`, sourceAttribute))
	}

	if diags.HasError() {
		return NewPlanInitializerScriptValueUnknown(), diags
	}

	return PlanInitializerScriptValue{
		Source: sourceVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewPlanInitializerScriptValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) PlanInitializerScriptValue {
	object, diags := NewPlanInitializerScriptValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewPlanInitializerScriptValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t PlanInitializerScriptType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewPlanInitializerScriptValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewPlanInitializerScriptValueUnknown(), nil
	}

	if in.IsNull() {
		return NewPlanInitializerScriptValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewPlanInitializerScriptValueMust(PlanInitializerScriptValue{}.AttributeTypes(ctx), attributes), nil
}

func (t PlanInitializerScriptType) ValueType(ctx context.Context) attr.Value {
	return PlanInitializerScriptValue{}
}

var _ basetypes.ObjectValuable = PlanInitializerScriptValue{}

type PlanInitializerScriptValue struct {
	Source basetypes.StringValue `tfsdk:"source"`
	state  attr.ValueState
}

func (v PlanInitializerScriptValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["source"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Source.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["source"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v PlanInitializerScriptValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v PlanInitializerScriptValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v PlanInitializerScriptValue) String() string {
	return "PlanInitializerScriptValue"
}

func (v PlanInitializerScriptValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"source": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"source": v.Source,
		})

	return objVal, diags
}

func (v PlanInitializerScriptValue) Equal(o attr.Value) bool {
	other, ok := o.(PlanInitializerScriptValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Source.Equal(other.Source) {
		return false
	}

	return true
}

func (v PlanInitializerScriptValue) Type(ctx context.Context) attr.Type {
	return PlanInitializerScriptType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v PlanInitializerScriptValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"source": basetypes.StringType{},
	}
}

func (v BeforeProvisioningRuleValue) ToApi_betaBeforeProvisioningRuleDto(ctx context.Context) (*api_beta.BeforeProvisioningRuleDto, diag.Diagnostics) {
	var diags diag.Diagnostics

	if v.IsNull() {
		return nil, diags
	}

	if v.IsUnknown() {
		diags.Append(diag.NewErrorDiagnostic(
			"BeforeProvisioningRuleValue Value Is Unknown",
			`"BeforeProvisioningRuleValue" is unknown.`,
		))

		return nil, diags
	}

	return &api_beta.BeforeProvisioningRuleDto{
		Id:   v.Id.ValueStringPointer(),
		Name: v.Name.ValueStringPointer(),
		Type: v.BeforeProvisioningRuleType.ValueStringPointer(),
	}, diags
}

func (v BeforeProvisioningRuleValue) FromApi_betaBeforeProvisioningRuleDto(ctx context.Context, apiObject *api_beta.BeforeProvisioningRuleDto) (BeforeProvisioningRuleValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	if apiObject == nil {
		return NewBeforeProvisioningRuleValueNull(), diags
	}

	return BeforeProvisioningRuleValue{
		Id:                         types.StringPointerValue(apiObject.Id),
		Name:                       types.StringPointerValue(apiObject.Name),
		BeforeProvisioningRuleType: types.StringPointerValue(apiObject.Type),
		state:                      attr.ValueStateKnown,
	}, diags
}

func (v ClusterRefValue) ToApi_betaSourceClusterDto(ctx context.Context) (*api_beta.SourceClusterDto, diag.Diagnostics) {
	var diags diag.Diagnostics

	if v.IsNull() {
		return nil, diags
	}

	if v.IsUnknown() {
		diags.Append(diag.NewErrorDiagnostic(
			"ClusterRefValue Value Is Unknown",
			`"ClusterRefValue" is unknown.`,
		))

		return nil, diags
	}

	return &api_beta.SourceClusterDto{
		Id:   v.Id.ValueStringPointer(),
		Name: v.Name.ValueStringPointer(),
		Type: v.ClusterRefType.ValueStringPointer(),
	}, diags
}

func (v ClusterRefValue) FromApi_betaSourceClusterDto(ctx context.Context, apiObject *api_beta.SourceClusterDto) (ClusterRefValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	if apiObject == nil {
		return NewClusterRefValueNull(), diags
	}

	return ClusterRefValue{
		Id:             types.StringPointerValue(apiObject.Id),
		Name:           types.StringPointerValue(apiObject.Name),
		ClusterRefType: types.StringPointerValue(apiObject.Type),
		state:          attr.ValueStateKnown,
	}, diags
}

func (v OwnerRefValue) ToApi_betaOwnerDto(ctx context.Context) (*api_beta.OwnerDto, diag.Diagnostics) {
	var diags diag.Diagnostics

	if v.IsNull() {
		return nil, diags
	}

	if v.IsUnknown() {
		diags.Append(diag.NewErrorDiagnostic(
			"OwnerRefValue Value Is Unknown",
			`"OwnerRefValue" is unknown.`,
		))

		return nil, diags
	}

	return &api_beta.OwnerDto{
		Id:   v.Id.ValueStringPointer(),
		Name: v.Name.ValueStringPointer(),
		Type: v.OwnerRefType.ValueStringPointer(),
	}, diags
}

func (v OwnerRefValue) FromApi_betaOwnerDto(ctx context.Context, apiObject *api_beta.OwnerDto) (OwnerRefValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	if apiObject == nil {
		return NewOwnerRefValueNull(), diags
	}

	return OwnerRefValue{
		Id:           types.StringPointerValue(apiObject.Id),
		Name:         types.StringPointerValue(apiObject.Name),
		OwnerRefType: types.StringPointerValue(apiObject.Type),
		state:        attr.ValueStateKnown,
	}, diags
}
