// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_sod_policy

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"github.com/sailpoint-oss/golang-sdk/v3/sod_policies"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func SodPolicyDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"compensating_controls": schema.StringAttribute{
				Computed:            true,
				Description:         "Optional compensating controls(Mitigating Controls)",
				MarkdownDescription: "Optional compensating controls(Mitigating Controls)",
			},
			"correction_advice": schema.StringAttribute{
				Computed:            true,
				Description:         "Optional correction advice",
				MarkdownDescription: "Optional correction advice",
			},
			"created": schema.StringAttribute{
				Computed:            true,
				Description:         "The time when this SOD policy is created.",
				MarkdownDescription: "The time when this SOD policy is created.",
			},
			"creator_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Policy's creator ID",
				MarkdownDescription: "Policy's creator ID",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "Optional description of the SOD policy",
				MarkdownDescription: "Optional description of the SOD policy",
			},
			"external_policy_reference": schema.StringAttribute{
				Computed:            true,
				Description:         "Optional External Policy Reference",
				MarkdownDescription: "Optional External Policy Reference",
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "The ID of the SOD Policy to retrieve.",
				MarkdownDescription: "The ID of the SOD Policy to retrieve.",
			},
			"modified": schema.StringAttribute{
				Computed:            true,
				Description:         "The time when this SOD policy is modified.",
				MarkdownDescription: "The time when this SOD policy is modified.",
			},
			"modifier_id": schema.StringAttribute{
				Computed:            true,
				Description:         "Policy's modifier ID",
				MarkdownDescription: "Policy's modifier ID",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "Policy Business Name",
				MarkdownDescription: "Policy Business Name",
			},
			"owner_ref": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed:            true,
						Description:         "Owner's ID.",
						MarkdownDescription: "Owner's ID.",
					},
					"name": schema.StringAttribute{
						Computed:            true,
						Description:         "Owner's name.",
						MarkdownDescription: "Owner's name.",
					},
					"type": schema.StringAttribute{
						Computed:            true,
						Description:         "Owner type.",
						MarkdownDescription: "Owner type.",
					},
				},
				CustomType: OwnerRefType{
					ObjectType: types.ObjectType{
						AttrTypes: OwnerRefValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "The owner of the SOD policy.",
				MarkdownDescription: "The owner of the SOD policy.",
			},
			"policy_query": schema.StringAttribute{
				Computed:            true,
				Description:         "Search query of the SOD policy",
				MarkdownDescription: "Search query of the SOD policy",
			},
			"scheduled": schema.BoolAttribute{
				Computed:            true,
				Description:         "defines whether a policy has been scheduled or not",
				MarkdownDescription: "defines whether a policy has been scheduled or not",
			},
			"state": schema.StringAttribute{
				Computed:            true,
				Description:         "whether the policy is enforced or not",
				MarkdownDescription: "whether the policy is enforced or not",
			},
			"tags": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "tags for this policy object",
				MarkdownDescription: "tags for this policy object",
			},
			"type": schema.StringAttribute{
				Computed:            true,
				Description:         "whether a policy is query based or conflicting access based",
				MarkdownDescription: "whether a policy is query based or conflicting access based",
			},
		},
	}
}

type SodPolicyModel struct {
	CompensatingControls    types.String  `tfsdk:"compensating_controls"`
	CorrectionAdvice        types.String  `tfsdk:"correction_advice"`
	Created                 types.String  `tfsdk:"created"`
	CreatorId               types.String  `tfsdk:"creator_id"`
	Description             types.String  `tfsdk:"description"`
	ExternalPolicyReference types.String  `tfsdk:"external_policy_reference"`
	Id                      types.String  `tfsdk:"id"`
	Modified                types.String  `tfsdk:"modified"`
	ModifierId              types.String  `tfsdk:"modifier_id"`
	Name                    types.String  `tfsdk:"name"`
	OwnerRef                OwnerRefValue `tfsdk:"owner_ref"`
	PolicyQuery             types.String  `tfsdk:"policy_query"`
	Scheduled               types.Bool    `tfsdk:"scheduled"`
	State                   types.String  `tfsdk:"state"`
	Tags                    types.List    `tfsdk:"tags"`
	Type                    types.String  `tfsdk:"type"`
}

var _ basetypes.ObjectTypable = OwnerRefType{}

type OwnerRefType struct {
	basetypes.ObjectType
}

func (t OwnerRefType) Equal(o attr.Type) bool {
	other, ok := o.(OwnerRefType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t OwnerRefType) String() string {
	return "OwnerRefType"
}

func (t OwnerRefType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return OwnerRefValue{
		Id:           idVal,
		Name:         nameVal,
		OwnerRefType: typeVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewOwnerRefValueNull() OwnerRefValue {
	return OwnerRefValue{
		state: attr.ValueStateNull,
	}
}

func NewOwnerRefValueUnknown() OwnerRefValue {
	return OwnerRefValue{
		state: attr.ValueStateUnknown,
	}
}

func NewOwnerRefValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (OwnerRefValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing OwnerRefValue Attribute Value",
				"While creating a OwnerRefValue value, a missing attribute value was detected. "+
					"A OwnerRefValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OwnerRefValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid OwnerRefValue Attribute Type",
				"While creating a OwnerRefValue value, an invalid attribute value was detected. "+
					"A OwnerRefValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OwnerRefValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("OwnerRefValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra OwnerRefValue Attribute Value",
				"While creating a OwnerRefValue value, an extra attribute value was detected. "+
					"A OwnerRefValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra OwnerRefValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewOwnerRefValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewOwnerRefValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewOwnerRefValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewOwnerRefValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewOwnerRefValueUnknown(), diags
	}

	return OwnerRefValue{
		Id:           idVal,
		Name:         nameVal,
		OwnerRefType: typeVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewOwnerRefValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) OwnerRefValue {
	object, diags := NewOwnerRefValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewOwnerRefValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t OwnerRefType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewOwnerRefValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewOwnerRefValueUnknown(), nil
	}

	if in.IsNull() {
		return NewOwnerRefValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewOwnerRefValueMust(OwnerRefValue{}.AttributeTypes(ctx), attributes), nil
}

func (t OwnerRefType) ValueType(ctx context.Context) attr.Value {
	return OwnerRefValue{}
}

var _ basetypes.ObjectValuable = OwnerRefValue{}

type OwnerRefValue struct {
	Id           basetypes.StringValue `tfsdk:"id"`
	Name         basetypes.StringValue `tfsdk:"name"`
	OwnerRefType basetypes.StringValue `tfsdk:"type"`
	state        attr.ValueState
}

func (v OwnerRefValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.OwnerRefType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v OwnerRefValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v OwnerRefValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v OwnerRefValue) String() string {
	return "OwnerRefValue"
}

func (v OwnerRefValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":   v.Id,
			"name": v.Name,
			"type": v.OwnerRefType,
		})

	return objVal, diags
}

func (v OwnerRefValue) Equal(o attr.Value) bool {
	other, ok := o.(OwnerRefValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.OwnerRefType.Equal(other.OwnerRefType) {
		return false
	}

	return true
}

func (v OwnerRefValue) Type(ctx context.Context) attr.Type {
	return OwnerRefType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v OwnerRefValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}
}

func (v OwnerRefValue) ToApi_betaSodPolicyOwnerRef(ctx context.Context) (*sod_policies.SodPolicyOwnerRef, diag.Diagnostics) {
	var diags diag.Diagnostics

	if v.IsNull() {
		return nil, diags
	}

	if v.IsUnknown() {
		diags.Append(diag.NewErrorDiagnostic(
			"OwnerRefValue Value Is Unknown",
			`"OwnerRefValue" is unknown.`,
		))

		return nil, diags
	}

	return &sod_policies.SodPolicyOwnerRef{
		Id:   v.Id.ValueStringPointer(),
		Name: v.Name.ValueStringPointer(),
		Type: v.OwnerRefType.ValueStringPointer(),
	}, diags
}

func (v OwnerRefValue) FromApi_betaSodPolicyOwnerRef(ctx context.Context, apiObject *sod_policies.SodPolicyOwnerRef) (OwnerRefValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	if apiObject == nil {
		return NewOwnerRefValueNull(), diags
	}

	return OwnerRefValue{
		Id:           types.StringPointerValue(apiObject.Id),
		Name:         types.StringPointerValue(apiObject.Name),
		OwnerRefType: types.StringPointerValue(apiObject.Type),
		state:        attr.ValueStateKnown,
	}, diags
}
