// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package datasource_entitlement

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
)

func EntitlementDataSourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"access_model_metadata": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"attributes": schema.ListNestedAttribute{
						NestedObject: schema.NestedAttributeObject{
							Attributes: map[string]schema.Attribute{
								"description": schema.StringAttribute{
									Computed:            true,
									Description:         "Describes the metadata item",
									MarkdownDescription: "Describes the metadata item",
								},
								"key": schema.StringAttribute{
									Computed:            true,
									Description:         "Unique identifier for the metadata type",
									MarkdownDescription: "Unique identifier for the metadata type",
								},
								"multiselect": schema.BoolAttribute{
									Computed:            true,
									Description:         "Allows selecting multiple values",
									MarkdownDescription: "Allows selecting multiple values",
								},
								"name": schema.StringAttribute{
									Computed:            true,
									Description:         "Human readable name of the metadata type",
									MarkdownDescription: "Human readable name of the metadata type",
								},
								"object_types": schema.ListAttribute{
									ElementType:         types.StringType,
									Computed:            true,
									Description:         "The types of objects",
									MarkdownDescription: "The types of objects",
								},
								"status": schema.StringAttribute{
									Computed:            true,
									Description:         "The state of the metadata item",
									MarkdownDescription: "The state of the metadata item",
								},
								"type": schema.StringAttribute{
									Computed:            true,
									Description:         "The type of the metadata item",
									MarkdownDescription: "The type of the metadata item",
								},
								"values": schema.ListNestedAttribute{
									NestedObject: schema.NestedAttributeObject{
										Attributes: map[string]schema.Attribute{
											"name": schema.StringAttribute{
												Computed:            true,
												Description:         "Display name of the value",
												MarkdownDescription: "Display name of the value",
											},
											"status": schema.StringAttribute{
												Computed:            true,
												Description:         "The status of the individual value",
												MarkdownDescription: "The status of the individual value",
											},
											"value": schema.StringAttribute{
												Computed:            true,
												Description:         "The value to assign to the metdata item",
												MarkdownDescription: "The value to assign to the metdata item",
											},
										},
										CustomType: ValuesType{
											ObjectType: types.ObjectType{
												AttrTypes: ValuesValue{}.AttributeTypes(ctx),
											},
										},
									},
									Computed:            true,
									Description:         "The value to assign to the metadata item",
									MarkdownDescription: "The value to assign to the metadata item",
								},
							},
							CustomType: AttributesType{
								ObjectType: types.ObjectType{
									AttrTypes: AttributesValue{}.AttributeTypes(ctx),
								},
							},
						},
						Computed: true,
					},
				},
				CustomType: AccessModelMetadataType{
					ObjectType: types.ObjectType{
						AttrTypes: AccessModelMetadataValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "Additional data to classify the entitlement",
				MarkdownDescription: "Additional data to classify the entitlement",
			},
			"attribute": schema.StringAttribute{
				Computed:            true,
				Description:         "The entitlement attribute name",
				MarkdownDescription: "The entitlement attribute name",
			},
			"cloud_governed": schema.BoolAttribute{
				Computed:            true,
				Description:         "True if the entitlement is cloud governed",
				MarkdownDescription: "True if the entitlement is cloud governed",
			},
			"created": schema.StringAttribute{
				Computed:            true,
				Description:         "Time when the entitlement was created",
				MarkdownDescription: "Time when the entitlement was created",
			},
			"description": schema.StringAttribute{
				Computed:            true,
				Description:         "The description of the entitlement",
				MarkdownDescription: "The description of the entitlement",
			},
			"direct_permissions": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"rights": schema.ListAttribute{
							ElementType:         types.StringType,
							Computed:            true,
							Description:         "All the rights (e.g. actions) that this permission allows on the target",
							MarkdownDescription: "All the rights (e.g. actions) that this permission allows on the target",
						},
						"target": schema.StringAttribute{
							Computed:            true,
							Description:         "The target the permission would grants rights on.",
							MarkdownDescription: "The target the permission would grants rights on.",
						},
					},
					CustomType: DirectPermissionsType{
						ObjectType: types.ObjectType{
							AttrTypes: DirectPermissionsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed: true,
			},
			"id": schema.StringAttribute{
				Required:            true,
				Description:         "The entitlement ID",
				MarkdownDescription: "The entitlement ID",
			},
			"modified": schema.StringAttribute{
				Computed:            true,
				Description:         "Time when the entitlement was last modified",
				MarkdownDescription: "Time when the entitlement was last modified",
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "The entitlement name",
				MarkdownDescription: "The entitlement name",
			},
			"owner": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed:            true,
						Description:         "The identity ID",
						MarkdownDescription: "The identity ID",
					},
					"name": schema.StringAttribute{
						Computed:            true,
						Description:         "The display name of the identity",
						MarkdownDescription: "The display name of the identity",
					},
					"type": schema.StringAttribute{
						Computed:            true,
						Description:         "The type of object",
						MarkdownDescription: "The type of object",
					},
				},
				CustomType: OwnerType{
					ObjectType: types.ObjectType{
						AttrTypes: OwnerValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "The identity that owns the entitlement",
				MarkdownDescription: "The identity that owns the entitlement",
			},
			"privilege_level": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"direct": schema.StringAttribute{
						Computed:            true,
						Description:         "Direct privilege level assigned to the entitlement",
						MarkdownDescription: "Direct privilege level assigned to the entitlement",
					},
					"effective": schema.StringAttribute{
						Computed:            true,
						Description:         "Effective privilege level assigned to the entitlement",
						MarkdownDescription: "Effective privilege level assigned to the entitlement",
					},
					"inherited": schema.StringAttribute{
						Computed:            true,
						Description:         "Inherited privilege level on the entitlement, if any",
						MarkdownDescription: "Inherited privilege level on the entitlement, if any",
					},
					"set_by": schema.StringAttribute{
						Computed:            true,
						Description:         "User or process that set the privilege level",
						MarkdownDescription: "User or process that set the privilege level",
					},
					"set_by_type": schema.StringAttribute{
						Computed:            true,
						Description:         "Method by which the privilege level was set",
						MarkdownDescription: "Method by which the privilege level was set",
					},
				},
				CustomType: PrivilegeLevelType{
					ObjectType: types.ObjectType{
						AttrTypes: PrivilegeLevelValue{}.AttributeTypes(ctx),
					},
				},
				Computed:            true,
				Description:         "Privilege level of the entitlement",
				MarkdownDescription: "Privilege level of the entitlement",
			},
			"requestable": schema.BoolAttribute{
				Computed:            true,
				Description:         "True if the entitlement is able to be directly requested",
				MarkdownDescription: "True if the entitlement is able to be directly requested",
			},
			"segments": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "List of IDs of segments, if any, to which this Entitlement is assigned.",
				MarkdownDescription: "List of IDs of segments, if any, to which this Entitlement is assigned.",
			},
			"source": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"id": schema.StringAttribute{
						Computed:            true,
						Description:         "The source ID",
						MarkdownDescription: "The source ID",
					},
					"name": schema.StringAttribute{
						Computed:            true,
						Description:         "The source name",
						MarkdownDescription: "The source name",
					},
					"type": schema.StringAttribute{
						Computed:            true,
						Description:         "The source type, will always be \"SOURCE\"",
						MarkdownDescription: "The source type, will always be \"SOURCE\"",
					},
				},
				CustomType: SourceType{
					ObjectType: types.ObjectType{
						AttrTypes: SourceValue{}.AttributeTypes(ctx),
					},
				},
				Computed: true,
			},
			"source_schema_object_type": schema.StringAttribute{
				Computed:            true,
				Description:         "The object type of the entitlement from the source schema",
				MarkdownDescription: "The object type of the entitlement from the source schema",
			},
			"tags": schema.ListAttribute{
				ElementType:         types.StringType,
				Computed:            true,
				Description:         "List of tags assigned to the entitlement",
				MarkdownDescription: "List of tags assigned to the entitlement",
			},
			"value": schema.StringAttribute{
				Computed:            true,
				Description:         "The value of the entitlement",
				MarkdownDescription: "The value of the entitlement",
			},
		},
	}
}

type EntitlementModel struct {
	AccessModelMetadata    AccessModelMetadataValue `tfsdk:"access_model_metadata"`
	Attribute              types.String             `tfsdk:"attribute"`
	CloudGoverned          types.Bool               `tfsdk:"cloud_governed"`
	Created                types.String             `tfsdk:"created"`
	Description            types.String             `tfsdk:"description"`
	DirectPermissions      types.List               `tfsdk:"direct_permissions"`
	Id                     types.String             `tfsdk:"id"`
	Modified               types.String             `tfsdk:"modified"`
	Name                   types.String             `tfsdk:"name"`
	Owner                  OwnerValue               `tfsdk:"owner"`
	PrivilegeLevel         PrivilegeLevelValue      `tfsdk:"privilege_level"`
	Requestable            types.Bool               `tfsdk:"requestable"`
	Segments               types.List               `tfsdk:"segments"`
	Source                 SourceValue              `tfsdk:"source"`
	SourceSchemaObjectType types.String             `tfsdk:"source_schema_object_type"`
	Tags                   types.List               `tfsdk:"tags"`
	Value                  types.String             `tfsdk:"value"`
}

var _ basetypes.ObjectTypable = AccessModelMetadataType{}

type AccessModelMetadataType struct {
	basetypes.ObjectType
}

func (t AccessModelMetadataType) Equal(o attr.Type) bool {
	other, ok := o.(AccessModelMetadataType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AccessModelMetadataType) String() string {
	return "AccessModelMetadataType"
}

func (t AccessModelMetadataType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	attributesAttribute, ok := attributes["attributes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attributes is missing from object`)

		return nil, diags
	}

	attributesVal, ok := attributesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attributes expected to be basetypes.ListValue, was: %T`, attributesAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AccessModelMetadataValue{
		Attributes: attributesVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewAccessModelMetadataValueNull() AccessModelMetadataValue {
	return AccessModelMetadataValue{
		state: attr.ValueStateNull,
	}
}

func NewAccessModelMetadataValueUnknown() AccessModelMetadataValue {
	return AccessModelMetadataValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAccessModelMetadataValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AccessModelMetadataValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AccessModelMetadataValue Attribute Value",
				"While creating a AccessModelMetadataValue value, a missing attribute value was detected. "+
					"A AccessModelMetadataValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AccessModelMetadataValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AccessModelMetadataValue Attribute Type",
				"While creating a AccessModelMetadataValue value, an invalid attribute value was detected. "+
					"A AccessModelMetadataValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AccessModelMetadataValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AccessModelMetadataValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AccessModelMetadataValue Attribute Value",
				"While creating a AccessModelMetadataValue value, an extra attribute value was detected. "+
					"A AccessModelMetadataValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AccessModelMetadataValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAccessModelMetadataValueUnknown(), diags
	}

	attributesAttribute, ok := attributes["attributes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`attributes is missing from object`)

		return NewAccessModelMetadataValueUnknown(), diags
	}

	attributesVal, ok := attributesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`attributes expected to be basetypes.ListValue, was: %T`, attributesAttribute))
	}

	if diags.HasError() {
		return NewAccessModelMetadataValueUnknown(), diags
	}

	return AccessModelMetadataValue{
		Attributes: attributesVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewAccessModelMetadataValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AccessModelMetadataValue {
	object, diags := NewAccessModelMetadataValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAccessModelMetadataValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AccessModelMetadataType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAccessModelMetadataValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAccessModelMetadataValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAccessModelMetadataValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAccessModelMetadataValueMust(AccessModelMetadataValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AccessModelMetadataType) ValueType(ctx context.Context) attr.Value {
	return AccessModelMetadataValue{}
}

var _ basetypes.ObjectValuable = AccessModelMetadataValue{}

type AccessModelMetadataValue struct {
	Attributes basetypes.ListValue `tfsdk:"attributes"`
	state      attr.ValueState
}

func (v AccessModelMetadataValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["attributes"] = basetypes.ListType{
		ElemType: AttributesValue{}.Type(ctx),
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Attributes.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["attributes"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AccessModelMetadataValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AccessModelMetadataValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AccessModelMetadataValue) String() string {
	return "AccessModelMetadataValue"
}

func (v AccessModelMetadataValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := types.ListValueMust(
		AttributesType{
			basetypes.ObjectType{
				AttrTypes: AttributesValue{}.AttributeTypes(ctx),
			},
		},
		v.Attributes.Elements(),
	)

	if v.Attributes.IsNull() {
		attributes = types.ListNull(
			AttributesType{
				basetypes.ObjectType{
					AttrTypes: AttributesValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.Attributes.IsUnknown() {
		attributes = types.ListUnknown(
			AttributesType{
				basetypes.ObjectType{
					AttrTypes: AttributesValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	attributeTypes := map[string]attr.Type{
		"attributes": basetypes.ListType{
			ElemType: AttributesValue{}.Type(ctx),
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"attributes": attributes,
		})

	return objVal, diags
}

func (v AccessModelMetadataValue) Equal(o attr.Value) bool {
	other, ok := o.(AccessModelMetadataValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Attributes.Equal(other.Attributes) {
		return false
	}

	return true
}

func (v AccessModelMetadataValue) Type(ctx context.Context) attr.Type {
	return AccessModelMetadataType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AccessModelMetadataValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"attributes": basetypes.ListType{
			ElemType: AttributesValue{}.Type(ctx),
		},
	}
}

var _ basetypes.ObjectTypable = AttributesType{}

type AttributesType struct {
	basetypes.ObjectType
}

func (t AttributesType) Equal(o attr.Type) bool {
	other, ok := o.(AttributesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AttributesType) String() string {
	return "AttributesType"
}

func (t AttributesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return nil, diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return nil, diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	multiselectAttribute, ok := attributes["multiselect"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`multiselect is missing from object`)

		return nil, diags
	}

	multiselectVal, ok := multiselectAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`multiselect expected to be basetypes.BoolValue, was: %T`, multiselectAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	objectTypesAttribute, ok := attributes["object_types"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`object_types is missing from object`)

		return nil, diags
	}

	objectTypesVal, ok := objectTypesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`object_types expected to be basetypes.ListValue, was: %T`, objectTypesAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return nil, diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	valuesAttribute, ok := attributes["values"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`values is missing from object`)

		return nil, diags
	}

	valuesVal, ok := valuesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`values expected to be basetypes.ListValue, was: %T`, valuesAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AttributesValue{
		Description:    descriptionVal,
		Key:            keyVal,
		Multiselect:    multiselectVal,
		Name:           nameVal,
		ObjectTypes:    objectTypesVal,
		Status:         statusVal,
		AttributesType: typeVal,
		Values:         valuesVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewAttributesValueNull() AttributesValue {
	return AttributesValue{
		state: attr.ValueStateNull,
	}
}

func NewAttributesValueUnknown() AttributesValue {
	return AttributesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAttributesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AttributesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AttributesValue Attribute Value",
				"While creating a AttributesValue value, a missing attribute value was detected. "+
					"A AttributesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AttributesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AttributesValue Attribute Type",
				"While creating a AttributesValue value, an invalid attribute value was detected. "+
					"A AttributesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AttributesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AttributesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AttributesValue Attribute Value",
				"While creating a AttributesValue value, an extra attribute value was detected. "+
					"A AttributesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AttributesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAttributesValueUnknown(), diags
	}

	descriptionAttribute, ok := attributes["description"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`description is missing from object`)

		return NewAttributesValueUnknown(), diags
	}

	descriptionVal, ok := descriptionAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`description expected to be basetypes.StringValue, was: %T`, descriptionAttribute))
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return NewAttributesValueUnknown(), diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	multiselectAttribute, ok := attributes["multiselect"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`multiselect is missing from object`)

		return NewAttributesValueUnknown(), diags
	}

	multiselectVal, ok := multiselectAttribute.(basetypes.BoolValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`multiselect expected to be basetypes.BoolValue, was: %T`, multiselectAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewAttributesValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	objectTypesAttribute, ok := attributes["object_types"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`object_types is missing from object`)

		return NewAttributesValueUnknown(), diags
	}

	objectTypesVal, ok := objectTypesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`object_types expected to be basetypes.ListValue, was: %T`, objectTypesAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return NewAttributesValueUnknown(), diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewAttributesValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	valuesAttribute, ok := attributes["values"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`values is missing from object`)

		return NewAttributesValueUnknown(), diags
	}

	valuesVal, ok := valuesAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`values expected to be basetypes.ListValue, was: %T`, valuesAttribute))
	}

	if diags.HasError() {
		return NewAttributesValueUnknown(), diags
	}

	return AttributesValue{
		Description:    descriptionVal,
		Key:            keyVal,
		Multiselect:    multiselectVal,
		Name:           nameVal,
		ObjectTypes:    objectTypesVal,
		Status:         statusVal,
		AttributesType: typeVal,
		Values:         valuesVal,
		state:          attr.ValueStateKnown,
	}, diags
}

func NewAttributesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AttributesValue {
	object, diags := NewAttributesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAttributesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AttributesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAttributesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAttributesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAttributesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAttributesValueMust(AttributesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AttributesType) ValueType(ctx context.Context) attr.Value {
	return AttributesValue{}
}

var _ basetypes.ObjectValuable = AttributesValue{}

type AttributesValue struct {
	Description    basetypes.StringValue `tfsdk:"description"`
	Key            basetypes.StringValue `tfsdk:"key"`
	Multiselect    basetypes.BoolValue   `tfsdk:"multiselect"`
	Name           basetypes.StringValue `tfsdk:"name"`
	ObjectTypes    basetypes.ListValue   `tfsdk:"object_types"`
	Status         basetypes.StringValue `tfsdk:"status"`
	AttributesType basetypes.StringValue `tfsdk:"type"`
	Values         basetypes.ListValue   `tfsdk:"values"`
	state          attr.ValueState
}

func (v AttributesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 8)

	var val tftypes.Value
	var err error

	attrTypes["description"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["key"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["multiselect"] = basetypes.BoolType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["object_types"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["status"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["values"] = basetypes.ListType{
		ElemType: ValuesValue{}.Type(ctx),
	}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 8)

		val, err = v.Description.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["description"] = val

		val, err = v.Key.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["key"] = val

		val, err = v.Multiselect.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["multiselect"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.ObjectTypes.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["object_types"] = val

		val, err = v.Status.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["status"] = val

		val, err = v.AttributesType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		val, err = v.Values.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["values"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AttributesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AttributesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AttributesValue) String() string {
	return "AttributesValue"
}

func (v AttributesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	values := types.ListValueMust(
		ValuesType{
			basetypes.ObjectType{
				AttrTypes: ValuesValue{}.AttributeTypes(ctx),
			},
		},
		v.Values.Elements(),
	)

	if v.Values.IsNull() {
		values = types.ListNull(
			ValuesType{
				basetypes.ObjectType{
					AttrTypes: ValuesValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	if v.Values.IsUnknown() {
		values = types.ListUnknown(
			ValuesType{
				basetypes.ObjectType{
					AttrTypes: ValuesValue{}.AttributeTypes(ctx),
				},
			},
		)
	}

	var objectTypesVal basetypes.ListValue
	switch {
	case v.ObjectTypes.IsUnknown():
		objectTypesVal = types.ListUnknown(types.StringType)
	case v.ObjectTypes.IsNull():
		objectTypesVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		objectTypesVal, d = types.ListValue(types.StringType, v.ObjectTypes.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"description": basetypes.StringType{},
			"key":         basetypes.StringType{},
			"multiselect": basetypes.BoolType{},
			"name":        basetypes.StringType{},
			"object_types": basetypes.ListType{
				ElemType: types.StringType,
			},
			"status": basetypes.StringType{},
			"type":   basetypes.StringType{},
			"values": basetypes.ListType{
				ElemType: ValuesValue{}.Type(ctx),
			},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"description": basetypes.StringType{},
		"key":         basetypes.StringType{},
		"multiselect": basetypes.BoolType{},
		"name":        basetypes.StringType{},
		"object_types": basetypes.ListType{
			ElemType: types.StringType,
		},
		"status": basetypes.StringType{},
		"type":   basetypes.StringType{},
		"values": basetypes.ListType{
			ElemType: ValuesValue{}.Type(ctx),
		},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"description":  v.Description,
			"key":          v.Key,
			"multiselect":  v.Multiselect,
			"name":         v.Name,
			"object_types": objectTypesVal,
			"status":       v.Status,
			"type":         v.AttributesType,
			"values":       values,
		})

	return objVal, diags
}

func (v AttributesValue) Equal(o attr.Value) bool {
	other, ok := o.(AttributesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Description.Equal(other.Description) {
		return false
	}

	if !v.Key.Equal(other.Key) {
		return false
	}

	if !v.Multiselect.Equal(other.Multiselect) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.ObjectTypes.Equal(other.ObjectTypes) {
		return false
	}

	if !v.Status.Equal(other.Status) {
		return false
	}

	if !v.AttributesType.Equal(other.AttributesType) {
		return false
	}

	if !v.Values.Equal(other.Values) {
		return false
	}

	return true
}

func (v AttributesValue) Type(ctx context.Context) attr.Type {
	return AttributesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AttributesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"description": basetypes.StringType{},
		"key":         basetypes.StringType{},
		"multiselect": basetypes.BoolType{},
		"name":        basetypes.StringType{},
		"object_types": basetypes.ListType{
			ElemType: types.StringType,
		},
		"status": basetypes.StringType{},
		"type":   basetypes.StringType{},
		"values": basetypes.ListType{
			ElemType: ValuesValue{}.Type(ctx),
		},
	}
}

var _ basetypes.ObjectTypable = ValuesType{}

type ValuesType struct {
	basetypes.ObjectType
}

func (t ValuesType) Equal(o attr.Type) bool {
	other, ok := o.(ValuesType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ValuesType) String() string {
	return "ValuesType"
}

func (t ValuesType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return nil, diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	valueAttribute, ok := attributes["value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value is missing from object`)

		return nil, diags
	}

	valueVal, ok := valueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value expected to be basetypes.StringValue, was: %T`, valueAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ValuesValue{
		Name:   nameVal,
		Status: statusVal,
		Value:  valueVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewValuesValueNull() ValuesValue {
	return ValuesValue{
		state: attr.ValueStateNull,
	}
}

func NewValuesValueUnknown() ValuesValue {
	return ValuesValue{
		state: attr.ValueStateUnknown,
	}
}

func NewValuesValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ValuesValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ValuesValue Attribute Value",
				"While creating a ValuesValue value, a missing attribute value was detected. "+
					"A ValuesValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ValuesValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ValuesValue Attribute Type",
				"While creating a ValuesValue value, an invalid attribute value was detected. "+
					"A ValuesValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ValuesValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ValuesValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ValuesValue Attribute Value",
				"While creating a ValuesValue value, an extra attribute value was detected. "+
					"A ValuesValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ValuesValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewValuesValueUnknown(), diags
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewValuesValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	statusAttribute, ok := attributes["status"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`status is missing from object`)

		return NewValuesValueUnknown(), diags
	}

	statusVal, ok := statusAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`status expected to be basetypes.StringValue, was: %T`, statusAttribute))
	}

	valueAttribute, ok := attributes["value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value is missing from object`)

		return NewValuesValueUnknown(), diags
	}

	valueVal, ok := valueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value expected to be basetypes.StringValue, was: %T`, valueAttribute))
	}

	if diags.HasError() {
		return NewValuesValueUnknown(), diags
	}

	return ValuesValue{
		Name:   nameVal,
		Status: statusVal,
		Value:  valueVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewValuesValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ValuesValue {
	object, diags := NewValuesValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewValuesValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ValuesType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewValuesValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewValuesValueUnknown(), nil
	}

	if in.IsNull() {
		return NewValuesValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewValuesValueMust(ValuesValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ValuesType) ValueType(ctx context.Context) attr.Value {
	return ValuesValue{}
}

var _ basetypes.ObjectValuable = ValuesValue{}

type ValuesValue struct {
	Name   basetypes.StringValue `tfsdk:"name"`
	Status basetypes.StringValue `tfsdk:"status"`
	Value  basetypes.StringValue `tfsdk:"value"`
	state  attr.ValueState
}

func (v ValuesValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["status"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["value"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.Status.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["status"] = val

		val, err = v.Value.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["value"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ValuesValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ValuesValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ValuesValue) String() string {
	return "ValuesValue"
}

func (v ValuesValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"name":   basetypes.StringType{},
		"status": basetypes.StringType{},
		"value":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"name":   v.Name,
			"status": v.Status,
			"value":  v.Value,
		})

	return objVal, diags
}

func (v ValuesValue) Equal(o attr.Value) bool {
	other, ok := o.(ValuesValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.Status.Equal(other.Status) {
		return false
	}

	if !v.Value.Equal(other.Value) {
		return false
	}

	return true
}

func (v ValuesValue) Type(ctx context.Context) attr.Type {
	return ValuesType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ValuesValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"name":   basetypes.StringType{},
		"status": basetypes.StringType{},
		"value":  basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = DirectPermissionsType{}

type DirectPermissionsType struct {
	basetypes.ObjectType
}

func (t DirectPermissionsType) Equal(o attr.Type) bool {
	other, ok := o.(DirectPermissionsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t DirectPermissionsType) String() string {
	return "DirectPermissionsType"
}

func (t DirectPermissionsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	rightsAttribute, ok := attributes["rights"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rights is missing from object`)

		return nil, diags
	}

	rightsVal, ok := rightsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rights expected to be basetypes.ListValue, was: %T`, rightsAttribute))
	}

	targetAttribute, ok := attributes["target"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`target is missing from object`)

		return nil, diags
	}

	targetVal, ok := targetAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`target expected to be basetypes.StringValue, was: %T`, targetAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return DirectPermissionsValue{
		Rights: rightsVal,
		Target: targetVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewDirectPermissionsValueNull() DirectPermissionsValue {
	return DirectPermissionsValue{
		state: attr.ValueStateNull,
	}
}

func NewDirectPermissionsValueUnknown() DirectPermissionsValue {
	return DirectPermissionsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewDirectPermissionsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (DirectPermissionsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing DirectPermissionsValue Attribute Value",
				"While creating a DirectPermissionsValue value, a missing attribute value was detected. "+
					"A DirectPermissionsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DirectPermissionsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid DirectPermissionsValue Attribute Type",
				"While creating a DirectPermissionsValue value, an invalid attribute value was detected. "+
					"A DirectPermissionsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("DirectPermissionsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("DirectPermissionsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra DirectPermissionsValue Attribute Value",
				"While creating a DirectPermissionsValue value, an extra attribute value was detected. "+
					"A DirectPermissionsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra DirectPermissionsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewDirectPermissionsValueUnknown(), diags
	}

	rightsAttribute, ok := attributes["rights"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`rights is missing from object`)

		return NewDirectPermissionsValueUnknown(), diags
	}

	rightsVal, ok := rightsAttribute.(basetypes.ListValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`rights expected to be basetypes.ListValue, was: %T`, rightsAttribute))
	}

	targetAttribute, ok := attributes["target"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`target is missing from object`)

		return NewDirectPermissionsValueUnknown(), diags
	}

	targetVal, ok := targetAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`target expected to be basetypes.StringValue, was: %T`, targetAttribute))
	}

	if diags.HasError() {
		return NewDirectPermissionsValueUnknown(), diags
	}

	return DirectPermissionsValue{
		Rights: rightsVal,
		Target: targetVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewDirectPermissionsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) DirectPermissionsValue {
	object, diags := NewDirectPermissionsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewDirectPermissionsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t DirectPermissionsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewDirectPermissionsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewDirectPermissionsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewDirectPermissionsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewDirectPermissionsValueMust(DirectPermissionsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t DirectPermissionsType) ValueType(ctx context.Context) attr.Value {
	return DirectPermissionsValue{}
}

var _ basetypes.ObjectValuable = DirectPermissionsValue{}

type DirectPermissionsValue struct {
	Rights basetypes.ListValue   `tfsdk:"rights"`
	Target basetypes.StringValue `tfsdk:"target"`
	state  attr.ValueState
}

func (v DirectPermissionsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["rights"] = basetypes.ListType{
		ElemType: types.StringType,
	}.TerraformType(ctx)
	attrTypes["target"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Rights.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["rights"] = val

		val, err = v.Target.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["target"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v DirectPermissionsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v DirectPermissionsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v DirectPermissionsValue) String() string {
	return "DirectPermissionsValue"
}

func (v DirectPermissionsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	var rightsVal basetypes.ListValue
	switch {
	case v.Rights.IsUnknown():
		rightsVal = types.ListUnknown(types.StringType)
	case v.Rights.IsNull():
		rightsVal = types.ListNull(types.StringType)
	default:
		var d diag.Diagnostics
		rightsVal, d = types.ListValue(types.StringType, v.Rights.Elements())
		diags.Append(d...)
	}

	if diags.HasError() {
		return types.ObjectUnknown(map[string]attr.Type{
			"rights": basetypes.ListType{
				ElemType: types.StringType,
			},
			"target": basetypes.StringType{},
		}), diags
	}

	attributeTypes := map[string]attr.Type{
		"rights": basetypes.ListType{
			ElemType: types.StringType,
		},
		"target": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"rights": rightsVal,
			"target": v.Target,
		})

	return objVal, diags
}

func (v DirectPermissionsValue) Equal(o attr.Value) bool {
	other, ok := o.(DirectPermissionsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Rights.Equal(other.Rights) {
		return false
	}

	if !v.Target.Equal(other.Target) {
		return false
	}

	return true
}

func (v DirectPermissionsValue) Type(ctx context.Context) attr.Type {
	return DirectPermissionsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v DirectPermissionsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"rights": basetypes.ListType{
			ElemType: types.StringType,
		},
		"target": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = OwnerType{}

type OwnerType struct {
	basetypes.ObjectType
}

func (t OwnerType) Equal(o attr.Type) bool {
	other, ok := o.(OwnerType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t OwnerType) String() string {
	return "OwnerType"
}

func (t OwnerType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return OwnerValue{
		Id:        idVal,
		Name:      nameVal,
		OwnerType: typeVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewOwnerValueNull() OwnerValue {
	return OwnerValue{
		state: attr.ValueStateNull,
	}
}

func NewOwnerValueUnknown() OwnerValue {
	return OwnerValue{
		state: attr.ValueStateUnknown,
	}
}

func NewOwnerValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (OwnerValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing OwnerValue Attribute Value",
				"While creating a OwnerValue value, a missing attribute value was detected. "+
					"A OwnerValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OwnerValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid OwnerValue Attribute Type",
				"While creating a OwnerValue value, an invalid attribute value was detected. "+
					"A OwnerValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("OwnerValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("OwnerValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra OwnerValue Attribute Value",
				"While creating a OwnerValue value, an extra attribute value was detected. "+
					"A OwnerValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra OwnerValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewOwnerValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewOwnerValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewOwnerValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewOwnerValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewOwnerValueUnknown(), diags
	}

	return OwnerValue{
		Id:        idVal,
		Name:      nameVal,
		OwnerType: typeVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewOwnerValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) OwnerValue {
	object, diags := NewOwnerValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewOwnerValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t OwnerType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewOwnerValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewOwnerValueUnknown(), nil
	}

	if in.IsNull() {
		return NewOwnerValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewOwnerValueMust(OwnerValue{}.AttributeTypes(ctx), attributes), nil
}

func (t OwnerType) ValueType(ctx context.Context) attr.Value {
	return OwnerValue{}
}

var _ basetypes.ObjectValuable = OwnerValue{}

type OwnerValue struct {
	Id        basetypes.StringValue `tfsdk:"id"`
	Name      basetypes.StringValue `tfsdk:"name"`
	OwnerType basetypes.StringValue `tfsdk:"type"`
	state     attr.ValueState
}

func (v OwnerValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.OwnerType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v OwnerValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v OwnerValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v OwnerValue) String() string {
	return "OwnerValue"
}

func (v OwnerValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":   v.Id,
			"name": v.Name,
			"type": v.OwnerType,
		})

	return objVal, diags
}

func (v OwnerValue) Equal(o attr.Value) bool {
	other, ok := o.(OwnerValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.OwnerType.Equal(other.OwnerType) {
		return false
	}

	return true
}

func (v OwnerValue) Type(ctx context.Context) attr.Type {
	return OwnerType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v OwnerValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = PrivilegeLevelType{}

type PrivilegeLevelType struct {
	basetypes.ObjectType
}

func (t PrivilegeLevelType) Equal(o attr.Type) bool {
	other, ok := o.(PrivilegeLevelType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t PrivilegeLevelType) String() string {
	return "PrivilegeLevelType"
}

func (t PrivilegeLevelType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	directAttribute, ok := attributes["direct"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`direct is missing from object`)

		return nil, diags
	}

	directVal, ok := directAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`direct expected to be basetypes.StringValue, was: %T`, directAttribute))
	}

	effectiveAttribute, ok := attributes["effective"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`effective is missing from object`)

		return nil, diags
	}

	effectiveVal, ok := effectiveAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`effective expected to be basetypes.StringValue, was: %T`, effectiveAttribute))
	}

	inheritedAttribute, ok := attributes["inherited"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`inherited is missing from object`)

		return nil, diags
	}

	inheritedVal, ok := inheritedAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`inherited expected to be basetypes.StringValue, was: %T`, inheritedAttribute))
	}

	setByAttribute, ok := attributes["set_by"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`set_by is missing from object`)

		return nil, diags
	}

	setByVal, ok := setByAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`set_by expected to be basetypes.StringValue, was: %T`, setByAttribute))
	}

	setByTypeAttribute, ok := attributes["set_by_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`set_by_type is missing from object`)

		return nil, diags
	}

	setByTypeVal, ok := setByTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`set_by_type expected to be basetypes.StringValue, was: %T`, setByTypeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return PrivilegeLevelValue{
		Direct:    directVal,
		Effective: effectiveVal,
		Inherited: inheritedVal,
		SetBy:     setByVal,
		SetByType: setByTypeVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewPrivilegeLevelValueNull() PrivilegeLevelValue {
	return PrivilegeLevelValue{
		state: attr.ValueStateNull,
	}
}

func NewPrivilegeLevelValueUnknown() PrivilegeLevelValue {
	return PrivilegeLevelValue{
		state: attr.ValueStateUnknown,
	}
}

func NewPrivilegeLevelValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (PrivilegeLevelValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing PrivilegeLevelValue Attribute Value",
				"While creating a PrivilegeLevelValue value, a missing attribute value was detected. "+
					"A PrivilegeLevelValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PrivilegeLevelValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid PrivilegeLevelValue Attribute Type",
				"While creating a PrivilegeLevelValue value, an invalid attribute value was detected. "+
					"A PrivilegeLevelValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("PrivilegeLevelValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("PrivilegeLevelValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra PrivilegeLevelValue Attribute Value",
				"While creating a PrivilegeLevelValue value, an extra attribute value was detected. "+
					"A PrivilegeLevelValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra PrivilegeLevelValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewPrivilegeLevelValueUnknown(), diags
	}

	directAttribute, ok := attributes["direct"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`direct is missing from object`)

		return NewPrivilegeLevelValueUnknown(), diags
	}

	directVal, ok := directAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`direct expected to be basetypes.StringValue, was: %T`, directAttribute))
	}

	effectiveAttribute, ok := attributes["effective"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`effective is missing from object`)

		return NewPrivilegeLevelValueUnknown(), diags
	}

	effectiveVal, ok := effectiveAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`effective expected to be basetypes.StringValue, was: %T`, effectiveAttribute))
	}

	inheritedAttribute, ok := attributes["inherited"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`inherited is missing from object`)

		return NewPrivilegeLevelValueUnknown(), diags
	}

	inheritedVal, ok := inheritedAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`inherited expected to be basetypes.StringValue, was: %T`, inheritedAttribute))
	}

	setByAttribute, ok := attributes["set_by"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`set_by is missing from object`)

		return NewPrivilegeLevelValueUnknown(), diags
	}

	setByVal, ok := setByAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`set_by expected to be basetypes.StringValue, was: %T`, setByAttribute))
	}

	setByTypeAttribute, ok := attributes["set_by_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`set_by_type is missing from object`)

		return NewPrivilegeLevelValueUnknown(), diags
	}

	setByTypeVal, ok := setByTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`set_by_type expected to be basetypes.StringValue, was: %T`, setByTypeAttribute))
	}

	if diags.HasError() {
		return NewPrivilegeLevelValueUnknown(), diags
	}

	return PrivilegeLevelValue{
		Direct:    directVal,
		Effective: effectiveVal,
		Inherited: inheritedVal,
		SetBy:     setByVal,
		SetByType: setByTypeVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewPrivilegeLevelValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) PrivilegeLevelValue {
	object, diags := NewPrivilegeLevelValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewPrivilegeLevelValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t PrivilegeLevelType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewPrivilegeLevelValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewPrivilegeLevelValueUnknown(), nil
	}

	if in.IsNull() {
		return NewPrivilegeLevelValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewPrivilegeLevelValueMust(PrivilegeLevelValue{}.AttributeTypes(ctx), attributes), nil
}

func (t PrivilegeLevelType) ValueType(ctx context.Context) attr.Value {
	return PrivilegeLevelValue{}
}

var _ basetypes.ObjectValuable = PrivilegeLevelValue{}

type PrivilegeLevelValue struct {
	Direct    basetypes.StringValue `tfsdk:"direct"`
	Effective basetypes.StringValue `tfsdk:"effective"`
	Inherited basetypes.StringValue `tfsdk:"inherited"`
	SetBy     basetypes.StringValue `tfsdk:"set_by"`
	SetByType basetypes.StringValue `tfsdk:"set_by_type"`
	state     attr.ValueState
}

func (v PrivilegeLevelValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["direct"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["effective"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["inherited"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["set_by"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["set_by_type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.Direct.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["direct"] = val

		val, err = v.Effective.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["effective"] = val

		val, err = v.Inherited.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["inherited"] = val

		val, err = v.SetBy.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["set_by"] = val

		val, err = v.SetByType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["set_by_type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v PrivilegeLevelValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v PrivilegeLevelValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v PrivilegeLevelValue) String() string {
	return "PrivilegeLevelValue"
}

func (v PrivilegeLevelValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"direct":      basetypes.StringType{},
		"effective":   basetypes.StringType{},
		"inherited":   basetypes.StringType{},
		"set_by":      basetypes.StringType{},
		"set_by_type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"direct":      v.Direct,
			"effective":   v.Effective,
			"inherited":   v.Inherited,
			"set_by":      v.SetBy,
			"set_by_type": v.SetByType,
		})

	return objVal, diags
}

func (v PrivilegeLevelValue) Equal(o attr.Value) bool {
	other, ok := o.(PrivilegeLevelValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Direct.Equal(other.Direct) {
		return false
	}

	if !v.Effective.Equal(other.Effective) {
		return false
	}

	if !v.Inherited.Equal(other.Inherited) {
		return false
	}

	if !v.SetBy.Equal(other.SetBy) {
		return false
	}

	if !v.SetByType.Equal(other.SetByType) {
		return false
	}

	return true
}

func (v PrivilegeLevelValue) Type(ctx context.Context) attr.Type {
	return PrivilegeLevelType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v PrivilegeLevelValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"direct":      basetypes.StringType{},
		"effective":   basetypes.StringType{},
		"inherited":   basetypes.StringType{},
		"set_by":      basetypes.StringType{},
		"set_by_type": basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = SourceType{}

type SourceType struct {
	basetypes.ObjectType
}

func (t SourceType) Equal(o attr.Type) bool {
	other, ok := o.(SourceType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t SourceType) String() string {
	return "SourceType"
}

func (t SourceType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return nil, diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return nil, diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return nil, diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return SourceValue{
		Id:         idVal,
		Name:       nameVal,
		SourceType: typeVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewSourceValueNull() SourceValue {
	return SourceValue{
		state: attr.ValueStateNull,
	}
}

func NewSourceValueUnknown() SourceValue {
	return SourceValue{
		state: attr.ValueStateUnknown,
	}
}

func NewSourceValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (SourceValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing SourceValue Attribute Value",
				"While creating a SourceValue value, a missing attribute value was detected. "+
					"A SourceValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SourceValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid SourceValue Attribute Type",
				"While creating a SourceValue value, an invalid attribute value was detected. "+
					"A SourceValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("SourceValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("SourceValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra SourceValue Attribute Value",
				"While creating a SourceValue value, an extra attribute value was detected. "+
					"A SourceValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra SourceValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewSourceValueUnknown(), diags
	}

	idAttribute, ok := attributes["id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`id is missing from object`)

		return NewSourceValueUnknown(), diags
	}

	idVal, ok := idAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`id expected to be basetypes.StringValue, was: %T`, idAttribute))
	}

	nameAttribute, ok := attributes["name"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`name is missing from object`)

		return NewSourceValueUnknown(), diags
	}

	nameVal, ok := nameAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`name expected to be basetypes.StringValue, was: %T`, nameAttribute))
	}

	typeAttribute, ok := attributes["type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`type is missing from object`)

		return NewSourceValueUnknown(), diags
	}

	typeVal, ok := typeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`type expected to be basetypes.StringValue, was: %T`, typeAttribute))
	}

	if diags.HasError() {
		return NewSourceValueUnknown(), diags
	}

	return SourceValue{
		Id:         idVal,
		Name:       nameVal,
		SourceType: typeVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewSourceValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) SourceValue {
	object, diags := NewSourceValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewSourceValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t SourceType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewSourceValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewSourceValueUnknown(), nil
	}

	if in.IsNull() {
		return NewSourceValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewSourceValueMust(SourceValue{}.AttributeTypes(ctx), attributes), nil
}

func (t SourceType) ValueType(ctx context.Context) attr.Value {
	return SourceValue{}
}

var _ basetypes.ObjectValuable = SourceValue{}

type SourceValue struct {
	Id         basetypes.StringValue `tfsdk:"id"`
	Name       basetypes.StringValue `tfsdk:"name"`
	SourceType basetypes.StringValue `tfsdk:"type"`
	state      attr.ValueState
}

func (v SourceValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["name"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["type"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Id.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["id"] = val

		val, err = v.Name.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["name"] = val

		val, err = v.SourceType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["type"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v SourceValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v SourceValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v SourceValue) String() string {
	return "SourceValue"
}

func (v SourceValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"id":   v.Id,
			"name": v.Name,
			"type": v.SourceType,
		})

	return objVal, diags
}

func (v SourceValue) Equal(o attr.Value) bool {
	other, ok := o.(SourceValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Id.Equal(other.Id) {
		return false
	}

	if !v.Name.Equal(other.Name) {
		return false
	}

	if !v.SourceType.Equal(other.SourceType) {
		return false
	}

	return true
}

func (v SourceValue) Type(ctx context.Context) attr.Type {
	return SourceType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v SourceValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"id":   basetypes.StringType{},
		"name": basetypes.StringType{},
		"type": basetypes.StringType{},
	}
}
